//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosPDV.SRMenu {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class MenuType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControladorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuncionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Controlador {
            get {
                return this.ControladorField;
            }
            set {
                if ((object.ReferenceEquals(this.ControladorField, value) != true)) {
                    this.ControladorField = value;
                    this.RaisePropertyChanged("Controlador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Funcion {
            get {
                return this.FuncionField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncionField, value) != true)) {
                    this.FuncionField = value;
                    this.RaisePropertyChanged("Funcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuPadre {
            get {
                return this.MenuPadreField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuPadreField, value) != true)) {
                    this.MenuPadreField = value;
                    this.RaisePropertyChanged("MenuPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfilType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class PerfilType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class UsuarioType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExisteErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<DatosPDV.SRMenu.PerfilType> ListaPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMensaje {
            get {
                return this.ErrorMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMensajeField, value) != true)) {
                    this.ErrorMensajeField = value;
                    this.RaisePropertyChanged("ErrorMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExisteError {
            get {
                return this.ExisteErrorField;
            }
            set {
                if ((this.ExisteErrorField.Equals(value) != true)) {
                    this.ExisteErrorField = value;
                    this.RaisePropertyChanged("ExisteError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DatosPDV.SRMenu.PerfilType> ListaPerfil {
            get {
                return this.ListaPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaPerfilField, value) != true)) {
                    this.ListaPerfilField = value;
                    this.RaisePropertyChanged("ListaPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRMenu.IMenu")]
    public interface IMenu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenu/GetListaMenuSistema", ReplyAction="http://tempuri.org/IMenu/GetListaMenuSistemaResponse")]
        System.Collections.Generic.List<DatosPDV.SRMenu.MenuType> GetListaMenuSistema(bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenu/GetListaMenuSistema", ReplyAction="http://tempuri.org/IMenu/GetListaMenuSistemaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRMenu.MenuType>> GetListaMenuSistemaAsync(bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenu/GetListaMenuPerfil", ReplyAction="http://tempuri.org/IMenu/GetListaMenuPerfilResponse")]
        System.Collections.Generic.List<DatosPDV.SRMenu.MenuType> GetListaMenuPerfil(DatosPDV.SRMenu.PerfilType oPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenu/GetListaMenuPerfil", ReplyAction="http://tempuri.org/IMenu/GetListaMenuPerfilResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRMenu.MenuType>> GetListaMenuPerfilAsync(DatosPDV.SRMenu.PerfilType oPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenu/GetListaMenuUsuario", ReplyAction="http://tempuri.org/IMenu/GetListaMenuUsuarioResponse")]
        System.Collections.Generic.List<DatosPDV.SRMenu.MenuType> GetListaMenuUsuario(DatosPDV.SRMenu.UsuarioType oUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenu/GetListaMenuUsuario", ReplyAction="http://tempuri.org/IMenu/GetListaMenuUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRMenu.MenuType>> GetListaMenuUsuarioAsync(DatosPDV.SRMenu.UsuarioType oUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMenuChannel : DatosPDV.SRMenu.IMenu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MenuClient : System.ServiceModel.ClientBase<DatosPDV.SRMenu.IMenu>, DatosPDV.SRMenu.IMenu {
        
        public MenuClient() {
        }
        
        public MenuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MenuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<DatosPDV.SRMenu.MenuType> GetListaMenuSistema(bool activo) {
            return base.Channel.GetListaMenuSistema(activo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRMenu.MenuType>> GetListaMenuSistemaAsync(bool activo) {
            return base.Channel.GetListaMenuSistemaAsync(activo);
        }
        
        public System.Collections.Generic.List<DatosPDV.SRMenu.MenuType> GetListaMenuPerfil(DatosPDV.SRMenu.PerfilType oPerfil) {
            return base.Channel.GetListaMenuPerfil(oPerfil);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRMenu.MenuType>> GetListaMenuPerfilAsync(DatosPDV.SRMenu.PerfilType oPerfil) {
            return base.Channel.GetListaMenuPerfilAsync(oPerfil);
        }
        
        public System.Collections.Generic.List<DatosPDV.SRMenu.MenuType> GetListaMenuUsuario(DatosPDV.SRMenu.UsuarioType oUsuario) {
            return base.Channel.GetListaMenuUsuario(oUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRMenu.MenuType>> GetListaMenuUsuarioAsync(DatosPDV.SRMenu.UsuarioType oUsuario) {
            return base.Channel.GetListaMenuUsuarioAsync(oUsuario);
        }
    }
}
