//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosPDV.SRGarantia {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GarantiaType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class GarantiaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DiasVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocEntryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DocNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntidadNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpisodioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRGarantia.EstadoGarantia EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FichaClinicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenerarCartaDescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdAsignacionCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTrackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImpresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IndicadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroChequeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumDocBoletaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacienteAptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacienteComunaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacienteDireccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacienteNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacientePasaporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacienteRUTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsableAptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsableComunaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsableDireccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsableNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsablePasaporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsableRUTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> U_NumPagRecibField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comentario {
            get {
                return this.ComentarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentarioField, value) != true)) {
                    this.ComentarioField = value;
                    this.RaisePropertyChanged("Comentario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DiasVencimiento {
            get {
                return this.DiasVencimientoField;
            }
            set {
                if ((this.DiasVencimientoField.Equals(value) != true)) {
                    this.DiasVencimientoField = value;
                    this.RaisePropertyChanged("DiasVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocEntry {
            get {
                return this.DocEntryField;
            }
            set {
                if ((this.DocEntryField.Equals(value) != true)) {
                    this.DocEntryField = value;
                    this.RaisePropertyChanged("DocEntry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DocNum {
            get {
                return this.DocNumField;
            }
            set {
                if ((this.DocNumField.Equals(value) != true)) {
                    this.DocNumField = value;
                    this.RaisePropertyChanged("DocNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Entidad {
            get {
                return this.EntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadField, value) != true)) {
                    this.EntidadField = value;
                    this.RaisePropertyChanged("Entidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntidadNombre {
            get {
                return this.EntidadNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadNombreField, value) != true)) {
                    this.EntidadNombreField = value;
                    this.RaisePropertyChanged("EntidadNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Episodio {
            get {
                return this.EpisodioField;
            }
            set {
                if ((object.ReferenceEquals(this.EpisodioField, value) != true)) {
                    this.EpisodioField = value;
                    this.RaisePropertyChanged("Episodio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRGarantia.EstadoGarantia Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((this.FechaVencimientoField.Equals(value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FichaClinica {
            get {
                return this.FichaClinicaField;
            }
            set {
                if ((object.ReferenceEquals(this.FichaClinicaField, value) != true)) {
                    this.FichaClinicaField = value;
                    this.RaisePropertyChanged("FichaClinica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenerarCartaDescuento {
            get {
                return this.GenerarCartaDescuentoField;
            }
            set {
                if ((object.ReferenceEquals(this.GenerarCartaDescuentoField, value) != true)) {
                    this.GenerarCartaDescuentoField = value;
                    this.RaisePropertyChanged("GenerarCartaDescuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdAsignacionCaja {
            get {
                return this.IdAsignacionCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdAsignacionCajaField, value) != true)) {
                    this.IdAsignacionCajaField = value;
                    this.RaisePropertyChanged("IdAsignacionCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCaja {
            get {
                return this.IdCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCajaField, value) != true)) {
                    this.IdCajaField = value;
                    this.RaisePropertyChanged("IdCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTrack {
            get {
                return this.IdTrackField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTrackField, value) != true)) {
                    this.IdTrackField = value;
                    this.RaisePropertyChanged("IdTrack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impreso {
            get {
                return this.ImpresoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImpresoField, value) != true)) {
                    this.ImpresoField = value;
                    this.RaisePropertyChanged("Impreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Indicador {
            get {
                return this.IndicadorField;
            }
            set {
                if ((this.IndicadorField.Equals(value) != true)) {
                    this.IndicadorField = value;
                    this.RaisePropertyChanged("Indicador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroCheque {
            get {
                return this.NroChequeField;
            }
            set {
                if ((object.ReferenceEquals(this.NroChequeField, value) != true)) {
                    this.NroChequeField = value;
                    this.RaisePropertyChanged("NroCheque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumDocBoleta {
            get {
                return this.NumDocBoletaField;
            }
            set {
                if ((this.NumDocBoletaField.Equals(value) != true)) {
                    this.NumDocBoletaField = value;
                    this.RaisePropertyChanged("NumDocBoleta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PacienteApt {
            get {
                return this.PacienteAptField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteAptField, value) != true)) {
                    this.PacienteAptField = value;
                    this.RaisePropertyChanged("PacienteApt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PacienteComuna {
            get {
                return this.PacienteComunaField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteComunaField, value) != true)) {
                    this.PacienteComunaField = value;
                    this.RaisePropertyChanged("PacienteComuna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PacienteDirecc {
            get {
                return this.PacienteDireccField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteDireccField, value) != true)) {
                    this.PacienteDireccField = value;
                    this.RaisePropertyChanged("PacienteDirecc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PacienteNombre {
            get {
                return this.PacienteNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteNombreField, value) != true)) {
                    this.PacienteNombreField = value;
                    this.RaisePropertyChanged("PacienteNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PacientePasaporte {
            get {
                return this.PacientePasaporteField;
            }
            set {
                if ((object.ReferenceEquals(this.PacientePasaporteField, value) != true)) {
                    this.PacientePasaporteField = value;
                    this.RaisePropertyChanged("PacientePasaporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PacienteRUT {
            get {
                return this.PacienteRUTField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteRUTField, value) != true)) {
                    this.PacienteRUTField = value;
                    this.RaisePropertyChanged("PacienteRUT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsableApt {
            get {
                return this.ResponsableAptField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsableAptField, value) != true)) {
                    this.ResponsableAptField = value;
                    this.RaisePropertyChanged("ResponsableApt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsableComuna {
            get {
                return this.ResponsableComunaField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsableComunaField, value) != true)) {
                    this.ResponsableComunaField = value;
                    this.RaisePropertyChanged("ResponsableComuna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsableDirecc {
            get {
                return this.ResponsableDireccField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsableDireccField, value) != true)) {
                    this.ResponsableDireccField = value;
                    this.RaisePropertyChanged("ResponsableDirecc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsableNombre {
            get {
                return this.ResponsableNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsableNombreField, value) != true)) {
                    this.ResponsableNombreField = value;
                    this.RaisePropertyChanged("ResponsableNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsablePasaporte {
            get {
                return this.ResponsablePasaporteField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsablePasaporteField, value) != true)) {
                    this.ResponsablePasaporteField = value;
                    this.RaisePropertyChanged("ResponsablePasaporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsableRUT {
            get {
                return this.ResponsableRUTField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsableRUTField, value) != true)) {
                    this.ResponsableRUTField = value;
                    this.RaisePropertyChanged("ResponsableRUT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> U_NumPagRecib {
            get {
                return this.U_NumPagRecibField;
            }
            set {
                if ((this.U_NumPagRecibField.Equals(value) != true)) {
                    this.U_NumPagRecibField = value;
                    this.RaisePropertyChanged("U_NumPagRecib");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoGarantia", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    public enum EstadoGarantia : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vencido = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoAsignado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Devuelto = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aplicado = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lleno = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Protesto = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Anulado = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GarantiaFilterType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class GarantiaFilterType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocEntryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DocNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpisodioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRGarantia.EstadoGarantia EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdAsignacionCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacienteRUTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsableRUTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupervisorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocEntry {
            get {
                return this.DocEntryField;
            }
            set {
                if ((this.DocEntryField.Equals(value) != true)) {
                    this.DocEntryField = value;
                    this.RaisePropertyChanged("DocEntry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DocNum {
            get {
                return this.DocNumField;
            }
            set {
                if ((this.DocNumField.Equals(value) != true)) {
                    this.DocNumField = value;
                    this.RaisePropertyChanged("DocNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Episodio {
            get {
                return this.EpisodioField;
            }
            set {
                if ((object.ReferenceEquals(this.EpisodioField, value) != true)) {
                    this.EpisodioField = value;
                    this.RaisePropertyChanged("Episodio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRGarantia.EstadoGarantia Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFinal {
            get {
                return this.FechaFinalField;
            }
            set {
                if ((this.FechaFinalField.Equals(value) != true)) {
                    this.FechaFinalField = value;
                    this.RaisePropertyChanged("FechaFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdAsignacionCaja {
            get {
                return this.IdAsignacionCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdAsignacionCajaField, value) != true)) {
                    this.IdAsignacionCajaField = value;
                    this.RaisePropertyChanged("IdAsignacionCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PacienteRUT {
            get {
                return this.PacienteRUTField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteRUTField, value) != true)) {
                    this.PacienteRUTField = value;
                    this.RaisePropertyChanged("PacienteRUT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponsableRUT {
            get {
                return this.ResponsableRUTField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsableRUTField, value) != true)) {
                    this.ResponsableRUTField = value;
                    this.RaisePropertyChanged("ResponsableRUT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupervisorId {
            get {
                return this.SupervisorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SupervisorIdField, value) != true)) {
                    this.SupervisorIdField = value;
                    this.RaisePropertyChanged("SupervisorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioIdField, value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class RespuestaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocEntryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTrackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocEntry {
            get {
                return this.DocEntryField;
            }
            set {
                if ((object.ReferenceEquals(this.DocEntryField, value) != true)) {
                    this.DocEntryField = value;
                    this.RaisePropertyChanged("DocEntry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocNum {
            get {
                return this.DocNumField;
            }
            set {
                if ((object.ReferenceEquals(this.DocNumField, value) != true)) {
                    this.DocNumField = value;
                    this.RaisePropertyChanged("DocNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTrack {
            get {
                return this.IdTrackField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTrackField, value) != true)) {
                    this.IdTrackField = value;
                    this.RaisePropertyChanged("IdTrack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRGarantia.IGarantia")]
    public interface IGarantia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarantia/GetGarantiaById", ReplyAction="http://tempuri.org/IGarantia/GetGarantiaByIdResponse")]
        DatosPDV.SRGarantia.GarantiaType GetGarantiaById(int idGarantia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarantia/GetGarantiaById", ReplyAction="http://tempuri.org/IGarantia/GetGarantiaByIdResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRGarantia.GarantiaType> GetGarantiaByIdAsync(int idGarantia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarantia/GetListaGarantiaByFiltro", ReplyAction="http://tempuri.org/IGarantia/GetListaGarantiaByFiltroResponse")]
        DatosPDV.SRGarantia.GarantiaType[] GetListaGarantiaByFiltro(DatosPDV.SRGarantia.GarantiaFilterType filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarantia/GetListaGarantiaByFiltro", ReplyAction="http://tempuri.org/IGarantia/GetListaGarantiaByFiltroResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRGarantia.GarantiaType[]> GetListaGarantiaByFiltroAsync(DatosPDV.SRGarantia.GarantiaFilterType filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarantia/AdministrarGarantia", ReplyAction="http://tempuri.org/IGarantia/AdministrarGarantiaResponse")]
        DatosPDV.SRGarantia.RespuestaType AdministrarGarantia(DatosPDV.SRGarantia.GarantiaType garantia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarantia/AdministrarGarantia", ReplyAction="http://tempuri.org/IGarantia/AdministrarGarantiaResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRGarantia.RespuestaType> AdministrarGarantiaAsync(DatosPDV.SRGarantia.GarantiaType garantia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarantia/CambiarEstadoGarantia", ReplyAction="http://tempuri.org/IGarantia/CambiarEstadoGarantiaResponse")]
        DatosPDV.SRGarantia.RespuestaType CambiarEstadoGarantia(int GarantiaId, DatosPDV.SRGarantia.EstadoGarantia estado, string observacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarantia/CambiarEstadoGarantia", ReplyAction="http://tempuri.org/IGarantia/CambiarEstadoGarantiaResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRGarantia.RespuestaType> CambiarEstadoGarantiaAsync(int GarantiaId, DatosPDV.SRGarantia.EstadoGarantia estado, string observacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarantia/AplicarAnticipoBoleta", ReplyAction="http://tempuri.org/IGarantia/AplicarAnticipoBoletaResponse")]
        DatosPDV.SRGarantia.RespuestaType AplicarAnticipoBoleta(DatosPDV.SRGarantia.GarantiaType gar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarantia/AplicarAnticipoBoleta", ReplyAction="http://tempuri.org/IGarantia/AplicarAnticipoBoletaResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRGarantia.RespuestaType> AplicarAnticipoBoletaAsync(DatosPDV.SRGarantia.GarantiaType gar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGarantiaChannel : DatosPDV.SRGarantia.IGarantia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GarantiaClient : System.ServiceModel.ClientBase<DatosPDV.SRGarantia.IGarantia>, DatosPDV.SRGarantia.IGarantia {
        
        public GarantiaClient() {
        }
        
        public GarantiaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GarantiaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GarantiaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GarantiaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DatosPDV.SRGarantia.GarantiaType GetGarantiaById(int idGarantia) {
            return base.Channel.GetGarantiaById(idGarantia);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRGarantia.GarantiaType> GetGarantiaByIdAsync(int idGarantia) {
            return base.Channel.GetGarantiaByIdAsync(idGarantia);
        }
        
        public DatosPDV.SRGarantia.GarantiaType[] GetListaGarantiaByFiltro(DatosPDV.SRGarantia.GarantiaFilterType filtro) {
            return base.Channel.GetListaGarantiaByFiltro(filtro);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRGarantia.GarantiaType[]> GetListaGarantiaByFiltroAsync(DatosPDV.SRGarantia.GarantiaFilterType filtro) {
            return base.Channel.GetListaGarantiaByFiltroAsync(filtro);
        }
        
        public DatosPDV.SRGarantia.RespuestaType AdministrarGarantia(DatosPDV.SRGarantia.GarantiaType garantia) {
            return base.Channel.AdministrarGarantia(garantia);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRGarantia.RespuestaType> AdministrarGarantiaAsync(DatosPDV.SRGarantia.GarantiaType garantia) {
            return base.Channel.AdministrarGarantiaAsync(garantia);
        }
        
        public DatosPDV.SRGarantia.RespuestaType CambiarEstadoGarantia(int GarantiaId, DatosPDV.SRGarantia.EstadoGarantia estado, string observacion) {
            return base.Channel.CambiarEstadoGarantia(GarantiaId, estado, observacion);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRGarantia.RespuestaType> CambiarEstadoGarantiaAsync(int GarantiaId, DatosPDV.SRGarantia.EstadoGarantia estado, string observacion) {
            return base.Channel.CambiarEstadoGarantiaAsync(GarantiaId, estado, observacion);
        }
        
        public DatosPDV.SRGarantia.RespuestaType AplicarAnticipoBoleta(DatosPDV.SRGarantia.GarantiaType gar) {
            return base.Channel.AplicarAnticipoBoleta(gar);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRGarantia.RespuestaType> AplicarAnticipoBoletaAsync(DatosPDV.SRGarantia.GarantiaType gar) {
            return base.Channel.AplicarAnticipoBoletaAsync(gar);
        }
    }
}
