//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosPDV.SRPerfil {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfilType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class PerfilType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class UsuarioType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExisteErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<DatosPDV.SRPerfil.PerfilType> ListaPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMensaje {
            get {
                return this.ErrorMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMensajeField, value) != true)) {
                    this.ErrorMensajeField = value;
                    this.RaisePropertyChanged("ErrorMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExisteError {
            get {
                return this.ExisteErrorField;
            }
            set {
                if ((this.ExisteErrorField.Equals(value) != true)) {
                    this.ExisteErrorField = value;
                    this.RaisePropertyChanged("ExisteError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DatosPDV.SRPerfil.PerfilType> ListaPerfil {
            get {
                return this.ListaPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaPerfilField, value) != true)) {
                    this.ListaPerfilField = value;
                    this.RaisePropertyChanged("ListaPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRPerfil.IPerfil")]
    public interface IPerfil {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfil/GetListaPerfil", ReplyAction="http://tempuri.org/IPerfil/GetListaPerfilResponse")]
        System.Collections.Generic.List<DatosPDV.SRPerfil.PerfilType> GetListaPerfil(bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfil/GetListaPerfil", ReplyAction="http://tempuri.org/IPerfil/GetListaPerfilResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRPerfil.PerfilType>> GetListaPerfilAsync(bool activo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfil/GetListaPerfilUsuario", ReplyAction="http://tempuri.org/IPerfil/GetListaPerfilUsuarioResponse")]
        System.Collections.Generic.List<DatosPDV.SRPerfil.PerfilType> GetListaPerfilUsuario(DatosPDV.SRPerfil.UsuarioType oUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfil/GetListaPerfilUsuario", ReplyAction="http://tempuri.org/IPerfil/GetListaPerfilUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRPerfil.PerfilType>> GetListaPerfilUsuarioAsync(DatosPDV.SRPerfil.UsuarioType oUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPerfilChannel : DatosPDV.SRPerfil.IPerfil, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PerfilClient : System.ServiceModel.ClientBase<DatosPDV.SRPerfil.IPerfil>, DatosPDV.SRPerfil.IPerfil {
        
        public PerfilClient() {
        }
        
        public PerfilClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PerfilClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerfilClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerfilClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<DatosPDV.SRPerfil.PerfilType> GetListaPerfil(bool activo) {
            return base.Channel.GetListaPerfil(activo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRPerfil.PerfilType>> GetListaPerfilAsync(bool activo) {
            return base.Channel.GetListaPerfilAsync(activo);
        }
        
        public System.Collections.Generic.List<DatosPDV.SRPerfil.PerfilType> GetListaPerfilUsuario(DatosPDV.SRPerfil.UsuarioType oUsuario) {
            return base.Channel.GetListaPerfilUsuario(oUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRPerfil.PerfilType>> GetListaPerfilUsuarioAsync(DatosPDV.SRPerfil.UsuarioType oUsuario) {
            return base.Channel.GetListaPerfilUsuarioAsync(oUsuario);
        }
    }
}
