//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosPDV.SRNoObject {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoObjectListType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class NoObjectListType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.NoObjectType[] BancosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.NoObjectType[] ComunasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.NoObjectType[] EstadoAsignacionCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.NoObjectType[] EstadoDetalleNominaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.NoObjectType[] EstadoGarantiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.NoObjectType[] FuncionalidadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.NoObjectType[] FuncionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.MetodoPagoType[] MetodosDePagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.NoObjectType[] MotivoAnulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.NoObjectType[] PisosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.NoObjectType[] SeccionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.NoObjectType[] TarjetasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.NoObjectType[] TipoDocumentoDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.NoObjectType[] TipoGarantiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.NoObjectType[] TipoNominaAdmisionistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNoObject.NoObjectType[] TipoNominaSupervisorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.NoObjectType[] Bancos {
            get {
                return this.BancosField;
            }
            set {
                if ((object.ReferenceEquals(this.BancosField, value) != true)) {
                    this.BancosField = value;
                    this.RaisePropertyChanged("Bancos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.NoObjectType[] Comunas {
            get {
                return this.ComunasField;
            }
            set {
                if ((object.ReferenceEquals(this.ComunasField, value) != true)) {
                    this.ComunasField = value;
                    this.RaisePropertyChanged("Comunas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.NoObjectType[] EstadoAsignacionCaja {
            get {
                return this.EstadoAsignacionCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoAsignacionCajaField, value) != true)) {
                    this.EstadoAsignacionCajaField = value;
                    this.RaisePropertyChanged("EstadoAsignacionCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.NoObjectType[] EstadoDetalleNomina {
            get {
                return this.EstadoDetalleNominaField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoDetalleNominaField, value) != true)) {
                    this.EstadoDetalleNominaField = value;
                    this.RaisePropertyChanged("EstadoDetalleNomina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.NoObjectType[] EstadoGarantia {
            get {
                return this.EstadoGarantiaField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoGarantiaField, value) != true)) {
                    this.EstadoGarantiaField = value;
                    this.RaisePropertyChanged("EstadoGarantia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.NoObjectType[] Funcionalidades {
            get {
                return this.FuncionalidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncionalidadesField, value) != true)) {
                    this.FuncionalidadesField = value;
                    this.RaisePropertyChanged("Funcionalidades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.NoObjectType[] Funciones {
            get {
                return this.FuncionesField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncionesField, value) != true)) {
                    this.FuncionesField = value;
                    this.RaisePropertyChanged("Funciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.MetodoPagoType[] MetodosDePago {
            get {
                return this.MetodosDePagoField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodosDePagoField, value) != true)) {
                    this.MetodosDePagoField = value;
                    this.RaisePropertyChanged("MetodosDePago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.NoObjectType[] MotivoAnulacion {
            get {
                return this.MotivoAnulacionField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoAnulacionField, value) != true)) {
                    this.MotivoAnulacionField = value;
                    this.RaisePropertyChanged("MotivoAnulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.NoObjectType[] Pisos {
            get {
                return this.PisosField;
            }
            set {
                if ((object.ReferenceEquals(this.PisosField, value) != true)) {
                    this.PisosField = value;
                    this.RaisePropertyChanged("Pisos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.NoObjectType[] Secciones {
            get {
                return this.SeccionesField;
            }
            set {
                if ((object.ReferenceEquals(this.SeccionesField, value) != true)) {
                    this.SeccionesField = value;
                    this.RaisePropertyChanged("Secciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.NoObjectType[] Tarjetas {
            get {
                return this.TarjetasField;
            }
            set {
                if ((object.ReferenceEquals(this.TarjetasField, value) != true)) {
                    this.TarjetasField = value;
                    this.RaisePropertyChanged("Tarjetas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.NoObjectType[] TipoDocumentoDetalle {
            get {
                return this.TipoDocumentoDetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoDetalleField, value) != true)) {
                    this.TipoDocumentoDetalleField = value;
                    this.RaisePropertyChanged("TipoDocumentoDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.NoObjectType[] TipoGarantia {
            get {
                return this.TipoGarantiaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoGarantiaField, value) != true)) {
                    this.TipoGarantiaField = value;
                    this.RaisePropertyChanged("TipoGarantia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.NoObjectType[] TipoNominaAdmisionista {
            get {
                return this.TipoNominaAdmisionistaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoNominaAdmisionistaField, value) != true)) {
                    this.TipoNominaAdmisionistaField = value;
                    this.RaisePropertyChanged("TipoNominaAdmisionista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNoObject.NoObjectType[] TipoNominaSupervisor {
            get {
                return this.TipoNominaSupervisorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoNominaSupervisorField, value) != true)) {
                    this.TipoNominaSupervisorField = value;
                    this.RaisePropertyChanged("TipoNominaSupervisor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoObjectType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class NoObjectType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetodoPagoType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class MetodoPagoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ChequeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EfectivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TransferenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Cheque {
            get {
                return this.ChequeField;
            }
            set {
                if ((this.ChequeField.Equals(value) != true)) {
                    this.ChequeField = value;
                    this.RaisePropertyChanged("Cheque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Efectivo {
            get {
                return this.EfectivoField;
            }
            set {
                if ((this.EfectivoField.Equals(value) != true)) {
                    this.EfectivoField = value;
                    this.RaisePropertyChanged("Efectivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Tarjeta {
            get {
                return this.TarjetaField;
            }
            set {
                if ((this.TarjetaField.Equals(value) != true)) {
                    this.TarjetaField = value;
                    this.RaisePropertyChanged("Tarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Transferencia {
            get {
                return this.TransferenciaField;
            }
            set {
                if ((this.TransferenciaField.Equals(value) != true)) {
                    this.TransferenciaField = value;
                    this.RaisePropertyChanged("Transferencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRNoObject.INoObject")]
    public interface INoObject {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoObject/GetListas", ReplyAction="http://tempuri.org/INoObject/GetListasResponse")]
        DatosPDV.SRNoObject.NoObjectListType GetListas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoObject/GetListas", ReplyAction="http://tempuri.org/INoObject/GetListasResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRNoObject.NoObjectListType> GetListasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoObject/GetListaCache", ReplyAction="http://tempuri.org/INoObject/GetListaCacheResponse")]
        DatosPDV.SRNoObject.NoObjectType[] GetListaCache();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoObject/GetListaCache", ReplyAction="http://tempuri.org/INoObject/GetListaCacheResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRNoObject.NoObjectType[]> GetListaCacheAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INoObjectChannel : DatosPDV.SRNoObject.INoObject, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NoObjectClient : System.ServiceModel.ClientBase<DatosPDV.SRNoObject.INoObject>, DatosPDV.SRNoObject.INoObject {
        
        public NoObjectClient() {
        }
        
        public NoObjectClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NoObjectClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoObjectClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoObjectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DatosPDV.SRNoObject.NoObjectListType GetListas() {
            return base.Channel.GetListas();
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRNoObject.NoObjectListType> GetListasAsync() {
            return base.Channel.GetListasAsync();
        }
        
        public DatosPDV.SRNoObject.NoObjectType[] GetListaCache() {
            return base.Channel.GetListaCache();
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRNoObject.NoObjectType[]> GetListaCacheAsync() {
            return base.Channel.GetListaCacheAsync();
        }
    }
}
