//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosPDV.SRNomina {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NominaDetalleType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class NominaDetalleType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdmisionistaNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CajaNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocEntryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpisodioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoResponsableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoSupervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaAprobacionResponsableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaAprobacionSupervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaOrdenAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FichaClinicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineaDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MontoPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroNominaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroNominaSupervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroOrdenAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroSAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionResponsableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionSupervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacienteCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacienteNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PacienteRutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubTipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoSAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitularNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitularRutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadCobroEpisodioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadCobroPacienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdmisionistaNombre {
            get {
                return this.AdmisionistaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.AdmisionistaNombreField, value) != true)) {
                    this.AdmisionistaNombreField = value;
                    this.RaisePropertyChanged("AdmisionistaNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CajaNombre {
            get {
                return this.CajaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.CajaNombreField, value) != true)) {
                    this.CajaNombreField = value;
                    this.RaisePropertyChanged("CajaNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocEntry {
            get {
                return this.DocEntryField;
            }
            set {
                if ((this.DocEntryField.Equals(value) != true)) {
                    this.DocEntryField = value;
                    this.RaisePropertyChanged("DocEntry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Episodio {
            get {
                return this.EpisodioField;
            }
            set {
                if ((object.ReferenceEquals(this.EpisodioField, value) != true)) {
                    this.EpisodioField = value;
                    this.RaisePropertyChanged("Episodio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoResponsable {
            get {
                return this.EstadoResponsableField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoResponsableField, value) != true)) {
                    this.EstadoResponsableField = value;
                    this.RaisePropertyChanged("EstadoResponsable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoSupervisor {
            get {
                return this.EstadoSupervisorField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoSupervisorField, value) != true)) {
                    this.EstadoSupervisorField = value;
                    this.RaisePropertyChanged("EstadoSupervisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaAprobacionResponsable {
            get {
                return this.FechaAprobacionResponsableField;
            }
            set {
                if ((this.FechaAprobacionResponsableField.Equals(value) != true)) {
                    this.FechaAprobacionResponsableField = value;
                    this.RaisePropertyChanged("FechaAprobacionResponsable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaAprobacionSupervisor {
            get {
                return this.FechaAprobacionSupervisorField;
            }
            set {
                if ((this.FechaAprobacionSupervisorField.Equals(value) != true)) {
                    this.FechaAprobacionSupervisorField = value;
                    this.RaisePropertyChanged("FechaAprobacionSupervisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaDocumento {
            get {
                return this.FechaDocumentoField;
            }
            set {
                if ((this.FechaDocumentoField.Equals(value) != true)) {
                    this.FechaDocumentoField = value;
                    this.RaisePropertyChanged("FechaDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaOrdenAtencion {
            get {
                return this.FechaOrdenAtencionField;
            }
            set {
                if ((this.FechaOrdenAtencionField.Equals(value) != true)) {
                    this.FechaOrdenAtencionField = value;
                    this.RaisePropertyChanged("FechaOrdenAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FichaClinica {
            get {
                return this.FichaClinicaField;
            }
            set {
                if ((object.ReferenceEquals(this.FichaClinicaField, value) != true)) {
                    this.FichaClinicaField = value;
                    this.RaisePropertyChanged("FichaClinica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineaDetalle {
            get {
                return this.LineaDetalleField;
            }
            set {
                if ((this.LineaDetalleField.Equals(value) != true)) {
                    this.LineaDetalleField = value;
                    this.RaisePropertyChanged("LineaDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MontoPago {
            get {
                return this.MontoPagoField;
            }
            set {
                if ((this.MontoPagoField.Equals(value) != true)) {
                    this.MontoPagoField = value;
                    this.RaisePropertyChanged("MontoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento {
            get {
                return this.NumeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoField, value) != true)) {
                    this.NumeroDocumentoField = value;
                    this.RaisePropertyChanged("NumeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroNomina {
            get {
                return this.NumeroNominaField;
            }
            set {
                if ((this.NumeroNominaField.Equals(value) != true)) {
                    this.NumeroNominaField = value;
                    this.RaisePropertyChanged("NumeroNomina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroNominaSupervisor {
            get {
                return this.NumeroNominaSupervisorField;
            }
            set {
                if ((this.NumeroNominaSupervisorField.Equals(value) != true)) {
                    this.NumeroNominaSupervisorField = value;
                    this.RaisePropertyChanged("NumeroNominaSupervisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroOrdenAtencion {
            get {
                return this.NumeroOrdenAtencionField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroOrdenAtencionField, value) != true)) {
                    this.NumeroOrdenAtencionField = value;
                    this.RaisePropertyChanged("NumeroOrdenAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroSAP {
            get {
                return this.NumeroSAPField;
            }
            set {
                if ((this.NumeroSAPField.Equals(value) != true)) {
                    this.NumeroSAPField = value;
                    this.RaisePropertyChanged("NumeroSAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionResponsable {
            get {
                return this.ObservacionResponsableField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionResponsableField, value) != true)) {
                    this.ObservacionResponsableField = value;
                    this.RaisePropertyChanged("ObservacionResponsable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionSupervisor {
            get {
                return this.ObservacionSupervisorField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionSupervisorField, value) != true)) {
                    this.ObservacionSupervisorField = value;
                    this.RaisePropertyChanged("ObservacionSupervisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PacienteCategoria {
            get {
                return this.PacienteCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteCategoriaField, value) != true)) {
                    this.PacienteCategoriaField = value;
                    this.RaisePropertyChanged("PacienteCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PacienteNombre {
            get {
                return this.PacienteNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteNombreField, value) != true)) {
                    this.PacienteNombreField = value;
                    this.RaisePropertyChanged("PacienteNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PacienteRut {
            get {
                return this.PacienteRutField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteRutField, value) != true)) {
                    this.PacienteRutField = value;
                    this.RaisePropertyChanged("PacienteRut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubTipoDocumento {
            get {
                return this.SubTipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.SubTipoDocumentoField, value) != true)) {
                    this.SubTipoDocumentoField = value;
                    this.RaisePropertyChanged("SubTipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumentoDescripcion {
            get {
                return this.TipoDocumentoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoDescripcionField, value) != true)) {
                    this.TipoDocumentoDescripcionField = value;
                    this.RaisePropertyChanged("TipoDocumentoDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumentoSAP {
            get {
                return this.TipoDocumentoSAPField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoSAPField, value) != true)) {
                    this.TipoDocumentoSAPField = value;
                    this.RaisePropertyChanged("TipoDocumentoSAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitularNombre {
            get {
                return this.TitularNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitularNombreField, value) != true)) {
                    this.TitularNombreField = value;
                    this.RaisePropertyChanged("TitularNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitularRut {
            get {
                return this.TitularRutField;
            }
            set {
                if ((object.ReferenceEquals(this.TitularRutField, value) != true)) {
                    this.TitularRutField = value;
                    this.RaisePropertyChanged("TitularRut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadCobroEpisodio {
            get {
                return this.UnidadCobroEpisodioField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadCobroEpisodioField, value) != true)) {
                    this.UnidadCobroEpisodioField = value;
                    this.RaisePropertyChanged("UnidadCobroEpisodio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadCobroPaciente {
            get {
                return this.UnidadCobroPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadCobroPacienteField, value) != true)) {
                    this.UnidadCobroPacienteField = value;
                    this.RaisePropertyChanged("UnidadCobroPaciente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class RespuestaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocEntryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTrackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocEntry {
            get {
                return this.DocEntryField;
            }
            set {
                if ((object.ReferenceEquals(this.DocEntryField, value) != true)) {
                    this.DocEntryField = value;
                    this.RaisePropertyChanged("DocEntry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocNum {
            get {
                return this.DocNumField;
            }
            set {
                if ((object.ReferenceEquals(this.DocNumField, value) != true)) {
                    this.DocNumField = value;
                    this.RaisePropertyChanged("DocNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTrack {
            get {
                return this.IdTrackField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTrackField, value) != true)) {
                    this.IdTrackField = value;
                    this.RaisePropertyChanged("IdTrack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NominaFilterType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class NominaFilterType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CajaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoDetalleNominaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaDesdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaHastaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NominaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroDesdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroHastaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OcultarAprobadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PisoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeccionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupervisorNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoNominaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioPerfilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CajaId {
            get {
                return this.CajaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CajaIdField, value) != true)) {
                    this.CajaIdField = value;
                    this.RaisePropertyChanged("CajaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoDetalleNomina {
            get {
                return this.EstadoDetalleNominaField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoDetalleNominaField, value) != true)) {
                    this.EstadoDetalleNominaField = value;
                    this.RaisePropertyChanged("EstadoDetalleNomina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaDesde {
            get {
                return this.FechaDesdeField;
            }
            set {
                if ((this.FechaDesdeField.Equals(value) != true)) {
                    this.FechaDesdeField = value;
                    this.RaisePropertyChanged("FechaDesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaHasta {
            get {
                return this.FechaHastaField;
            }
            set {
                if ((this.FechaHastaField.Equals(value) != true)) {
                    this.FechaHastaField = value;
                    this.RaisePropertyChanged("FechaHasta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NominaId {
            get {
                return this.NominaIdField;
            }
            set {
                if ((this.NominaIdField.Equals(value) != true)) {
                    this.NominaIdField = value;
                    this.RaisePropertyChanged("NominaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroDesde {
            get {
                return this.NumeroDesdeField;
            }
            set {
                if ((this.NumeroDesdeField.Equals(value) != true)) {
                    this.NumeroDesdeField = value;
                    this.RaisePropertyChanged("NumeroDesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroHasta {
            get {
                return this.NumeroHastaField;
            }
            set {
                if ((this.NumeroHastaField.Equals(value) != true)) {
                    this.NumeroHastaField = value;
                    this.RaisePropertyChanged("NumeroHasta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OcultarAprobados {
            get {
                return this.OcultarAprobadosField;
            }
            set {
                if ((this.OcultarAprobadosField.Equals(value) != true)) {
                    this.OcultarAprobadosField = value;
                    this.RaisePropertyChanged("OcultarAprobados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PisoId {
            get {
                return this.PisoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PisoIdField, value) != true)) {
                    this.PisoIdField = value;
                    this.RaisePropertyChanged("PisoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeccionId {
            get {
                return this.SeccionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SeccionIdField, value) != true)) {
                    this.SeccionIdField = value;
                    this.RaisePropertyChanged("SeccionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupervisorNombre {
            get {
                return this.SupervisorNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.SupervisorNombreField, value) != true)) {
                    this.SupervisorNombreField = value;
                    this.RaisePropertyChanged("SupervisorNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoAtencion {
            get {
                return this.TipoAtencionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoAtencionField, value) != true)) {
                    this.TipoAtencionField = value;
                    this.RaisePropertyChanged("TipoAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoNomina {
            get {
                return this.TipoNominaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoNominaField, value) != true)) {
                    this.TipoNominaField = value;
                    this.RaisePropertyChanged("TipoNomina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioIdField, value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioPerfil {
            get {
                return this.UsuarioPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioPerfilField, value) != true)) {
                    this.UsuarioPerfilField = value;
                    this.RaisePropertyChanged("UsuarioPerfil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NominaType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class NominaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsignacionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CajaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CajaNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRNomina.NominaDetalleType[] DetalleNominaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocEntryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroNominaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupervisorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupervisorNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoAntencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoAntencionDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoNominaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoNominaDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalDetalleAnuladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalDetalleAprobadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalDetallePendienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalDetalleRechazadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AsignacionId {
            get {
                return this.AsignacionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AsignacionIdField, value) != true)) {
                    this.AsignacionIdField = value;
                    this.RaisePropertyChanged("AsignacionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CajaId {
            get {
                return this.CajaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CajaIdField, value) != true)) {
                    this.CajaIdField = value;
                    this.RaisePropertyChanged("CajaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CajaNombre {
            get {
                return this.CajaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.CajaNombreField, value) != true)) {
                    this.CajaNombreField = value;
                    this.RaisePropertyChanged("CajaNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRNomina.NominaDetalleType[] DetalleNomina {
            get {
                return this.DetalleNominaField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleNominaField, value) != true)) {
                    this.DetalleNominaField = value;
                    this.RaisePropertyChanged("DetalleNomina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocEntry {
            get {
                return this.DocEntryField;
            }
            set {
                if ((this.DocEntryField.Equals(value) != true)) {
                    this.DocEntryField = value;
                    this.RaisePropertyChanged("DocEntry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroNomina {
            get {
                return this.NumeroNominaField;
            }
            set {
                if ((this.NumeroNominaField.Equals(value) != true)) {
                    this.NumeroNominaField = value;
                    this.RaisePropertyChanged("NumeroNomina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupervisorId {
            get {
                return this.SupervisorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SupervisorIdField, value) != true)) {
                    this.SupervisorIdField = value;
                    this.RaisePropertyChanged("SupervisorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupervisorNombre {
            get {
                return this.SupervisorNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.SupervisorNombreField, value) != true)) {
                    this.SupervisorNombreField = value;
                    this.RaisePropertyChanged("SupervisorNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoAntencion {
            get {
                return this.TipoAntencionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoAntencionField, value) != true)) {
                    this.TipoAntencionField = value;
                    this.RaisePropertyChanged("TipoAntencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoAntencionDescripcion {
            get {
                return this.TipoAntencionDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoAntencionDescripcionField, value) != true)) {
                    this.TipoAntencionDescripcionField = value;
                    this.RaisePropertyChanged("TipoAntencionDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoNomina {
            get {
                return this.TipoNominaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoNominaField, value) != true)) {
                    this.TipoNominaField = value;
                    this.RaisePropertyChanged("TipoNomina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoNominaDescripcion {
            get {
                return this.TipoNominaDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoNominaDescripcionField, value) != true)) {
                    this.TipoNominaDescripcionField = value;
                    this.RaisePropertyChanged("TipoNominaDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalDetalle {
            get {
                return this.TotalDetalleField;
            }
            set {
                if ((this.TotalDetalleField.Equals(value) != true)) {
                    this.TotalDetalleField = value;
                    this.RaisePropertyChanged("TotalDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalDetalleAnulado {
            get {
                return this.TotalDetalleAnuladoField;
            }
            set {
                if ((this.TotalDetalleAnuladoField.Equals(value) != true)) {
                    this.TotalDetalleAnuladoField = value;
                    this.RaisePropertyChanged("TotalDetalleAnulado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalDetalleAprobado {
            get {
                return this.TotalDetalleAprobadoField;
            }
            set {
                if ((this.TotalDetalleAprobadoField.Equals(value) != true)) {
                    this.TotalDetalleAprobadoField = value;
                    this.RaisePropertyChanged("TotalDetalleAprobado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalDetallePendiente {
            get {
                return this.TotalDetallePendienteField;
            }
            set {
                if ((this.TotalDetallePendienteField.Equals(value) != true)) {
                    this.TotalDetallePendienteField = value;
                    this.RaisePropertyChanged("TotalDetallePendiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalDetalleRechazado {
            get {
                return this.TotalDetalleRechazadoField;
            }
            set {
                if ((this.TotalDetalleRechazadoField.Equals(value) != true)) {
                    this.TotalDetalleRechazadoField = value;
                    this.RaisePropertyChanged("TotalDetalleRechazado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioIdField, value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioNombre {
            get {
                return this.UsuarioNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioNombreField, value) != true)) {
                    this.UsuarioNombreField = value;
                    this.RaisePropertyChanged("UsuarioNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRNomina.INomina")]
    public interface INomina {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomina/AdministrarNominaDetalleMasivo", ReplyAction="http://tempuri.org/INomina/AdministrarNominaDetalleMasivoResponse")]
        DatosPDV.SRNomina.RespuestaType AdministrarNominaDetalleMasivo(DatosPDV.SRNomina.NominaDetalleType[] detalles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomina/AdministrarNominaDetalleMasivo", ReplyAction="http://tempuri.org/INomina/AdministrarNominaDetalleMasivoResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRNomina.RespuestaType> AdministrarNominaDetalleMasivoAsync(DatosPDV.SRNomina.NominaDetalleType[] detalles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomina/GenerarNominaSupervisor", ReplyAction="http://tempuri.org/INomina/GenerarNominaSupervisorResponse")]
        DatosPDV.SRNomina.RespuestaType GenerarNominaSupervisor(DatosPDV.SRNomina.NominaFilterType filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomina/GenerarNominaSupervisor", ReplyAction="http://tempuri.org/INomina/GenerarNominaSupervisorResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRNomina.RespuestaType> GenerarNominaSupervisorAsync(DatosPDV.SRNomina.NominaFilterType filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomina/GetNominaByParam", ReplyAction="http://tempuri.org/INomina/GetNominaByParamResponse")]
        DatosPDV.SRNomina.NominaType GetNominaByParam(int docEntryNomina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomina/GetNominaByParam", ReplyAction="http://tempuri.org/INomina/GetNominaByParamResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRNomina.NominaType> GetNominaByParamAsync(int docEntryNomina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomina/GetNominaSupervisorByParam", ReplyAction="http://tempuri.org/INomina/GetNominaSupervisorByParamResponse")]
        DatosPDV.SRNomina.NominaType GetNominaSupervisorByParam(int docEntryNomina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomina/GetNominaSupervisorByParam", ReplyAction="http://tempuri.org/INomina/GetNominaSupervisorByParamResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRNomina.NominaType> GetNominaSupervisorByParamAsync(int docEntryNomina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomina/GetListaNominas", ReplyAction="http://tempuri.org/INomina/GetListaNominasResponse")]
        DatosPDV.SRNomina.NominaType[] GetListaNominas(DatosPDV.SRNomina.NominaFilterType filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomina/GetListaNominas", ReplyAction="http://tempuri.org/INomina/GetListaNominasResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRNomina.NominaType[]> GetListaNominasAsync(DatosPDV.SRNomina.NominaFilterType filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomina/GetListaNominaDetalleAprobados", ReplyAction="http://tempuri.org/INomina/GetListaNominaDetalleAprobadosResponse")]
        DatosPDV.SRNomina.NominaDetalleType[] GetListaNominaDetalleAprobados(DatosPDV.SRNomina.NominaFilterType filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomina/GetListaNominaDetalleAprobados", ReplyAction="http://tempuri.org/INomina/GetListaNominaDetalleAprobadosResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRNomina.NominaDetalleType[]> GetListaNominaDetalleAprobadosAsync(DatosPDV.SRNomina.NominaFilterType filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomina/GetListaNominaSupervisor", ReplyAction="http://tempuri.org/INomina/GetListaNominaSupervisorResponse")]
        DatosPDV.SRNomina.NominaType[] GetListaNominaSupervisor(DatosPDV.SRNomina.NominaFilterType filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomina/GetListaNominaSupervisor", ReplyAction="http://tempuri.org/INomina/GetListaNominaSupervisorResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRNomina.NominaType[]> GetListaNominaSupervisorAsync(DatosPDV.SRNomina.NominaFilterType filtro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INominaChannel : DatosPDV.SRNomina.INomina, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NominaClient : System.ServiceModel.ClientBase<DatosPDV.SRNomina.INomina>, DatosPDV.SRNomina.INomina {
        
        public NominaClient() {
        }
        
        public NominaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NominaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NominaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NominaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DatosPDV.SRNomina.RespuestaType AdministrarNominaDetalleMasivo(DatosPDV.SRNomina.NominaDetalleType[] detalles) {
            return base.Channel.AdministrarNominaDetalleMasivo(detalles);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRNomina.RespuestaType> AdministrarNominaDetalleMasivoAsync(DatosPDV.SRNomina.NominaDetalleType[] detalles) {
            return base.Channel.AdministrarNominaDetalleMasivoAsync(detalles);
        }
        
        public DatosPDV.SRNomina.RespuestaType GenerarNominaSupervisor(DatosPDV.SRNomina.NominaFilterType filtro) {
            return base.Channel.GenerarNominaSupervisor(filtro);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRNomina.RespuestaType> GenerarNominaSupervisorAsync(DatosPDV.SRNomina.NominaFilterType filtro) {
            return base.Channel.GenerarNominaSupervisorAsync(filtro);
        }
        
        public DatosPDV.SRNomina.NominaType GetNominaByParam(int docEntryNomina) {
            return base.Channel.GetNominaByParam(docEntryNomina);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRNomina.NominaType> GetNominaByParamAsync(int docEntryNomina) {
            return base.Channel.GetNominaByParamAsync(docEntryNomina);
        }
        
        public DatosPDV.SRNomina.NominaType GetNominaSupervisorByParam(int docEntryNomina) {
            return base.Channel.GetNominaSupervisorByParam(docEntryNomina);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRNomina.NominaType> GetNominaSupervisorByParamAsync(int docEntryNomina) {
            return base.Channel.GetNominaSupervisorByParamAsync(docEntryNomina);
        }
        
        public DatosPDV.SRNomina.NominaType[] GetListaNominas(DatosPDV.SRNomina.NominaFilterType filtro) {
            return base.Channel.GetListaNominas(filtro);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRNomina.NominaType[]> GetListaNominasAsync(DatosPDV.SRNomina.NominaFilterType filtro) {
            return base.Channel.GetListaNominasAsync(filtro);
        }
        
        public DatosPDV.SRNomina.NominaDetalleType[] GetListaNominaDetalleAprobados(DatosPDV.SRNomina.NominaFilterType filtro) {
            return base.Channel.GetListaNominaDetalleAprobados(filtro);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRNomina.NominaDetalleType[]> GetListaNominaDetalleAprobadosAsync(DatosPDV.SRNomina.NominaFilterType filtro) {
            return base.Channel.GetListaNominaDetalleAprobadosAsync(filtro);
        }
        
        public DatosPDV.SRNomina.NominaType[] GetListaNominaSupervisor(DatosPDV.SRNomina.NominaFilterType filtro) {
            return base.Channel.GetListaNominaSupervisor(filtro);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRNomina.NominaType[]> GetListaNominaSupervisorAsync(DatosPDV.SRNomina.NominaFilterType filtro) {
            return base.Channel.GetListaNominaSupervisorAsync(filtro);
        }
    }
}
