//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosPDV.SRFolio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolioType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class FolioType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CajaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CajaNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadSegmentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadSegmentoPendientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsAnuladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsUltimoRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FolioFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FolioInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdFolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioSupervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoAnulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioSupervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRFolio.FolioSegmentoType[] SegmentosFolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosAnuladosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosDisponiblesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosUsadosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CajaId {
            get {
                return this.CajaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CajaIdField, value) != true)) {
                    this.CajaIdField = value;
                    this.RaisePropertyChanged("CajaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CajaNombre {
            get {
                return this.CajaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.CajaNombreField, value) != true)) {
                    this.CajaNombreField = value;
                    this.RaisePropertyChanged("CajaNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CantidadSegmento {
            get {
                return this.CantidadSegmentoField;
            }
            set {
                if ((this.CantidadSegmentoField.Equals(value) != true)) {
                    this.CantidadSegmentoField = value;
                    this.RaisePropertyChanged("CantidadSegmento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CantidadSegmentoPendientes {
            get {
                return this.CantidadSegmentoPendientesField;
            }
            set {
                if ((this.CantidadSegmentoPendientesField.Equals(value) != true)) {
                    this.CantidadSegmentoPendientesField = value;
                    this.RaisePropertyChanged("CantidadSegmentoPendientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsAnulado {
            get {
                return this.EsAnuladoField;
            }
            set {
                if ((this.EsAnuladoField.Equals(value) != true)) {
                    this.EsAnuladoField = value;
                    this.RaisePropertyChanged("EsAnulado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsUltimoRegistro {
            get {
                return this.EsUltimoRegistroField;
            }
            set {
                if ((this.EsUltimoRegistroField.Equals(value) != true)) {
                    this.EsUltimoRegistroField = value;
                    this.RaisePropertyChanged("EsUltimoRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFolio {
            get {
                return this.FechaFolioField;
            }
            set {
                if ((this.FechaFolioField.Equals(value) != true)) {
                    this.FechaFolioField = value;
                    this.RaisePropertyChanged("FechaFolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FolioFinal {
            get {
                return this.FolioFinalField;
            }
            set {
                if ((this.FolioFinalField.Equals(value) != true)) {
                    this.FolioFinalField = value;
                    this.RaisePropertyChanged("FolioFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FolioInicial {
            get {
                return this.FolioInicialField;
            }
            set {
                if ((this.FolioInicialField.Equals(value) != true)) {
                    this.FolioInicialField = value;
                    this.RaisePropertyChanged("FolioInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdFolio {
            get {
                return this.IdFolioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdFolioField, value) != true)) {
                    this.IdFolioField = value;
                    this.RaisePropertyChanged("IdFolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuarioCreacion {
            get {
                return this.IdUsuarioCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioCreacionField, value) != true)) {
                    this.IdUsuarioCreacionField = value;
                    this.RaisePropertyChanged("IdUsuarioCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuarioSupervisor {
            get {
                return this.IdUsuarioSupervisorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioSupervisorField, value) != true)) {
                    this.IdUsuarioSupervisorField = value;
                    this.RaisePropertyChanged("IdUsuarioSupervisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoAnulacion {
            get {
                return this.MotivoAnulacionField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoAnulacionField, value) != true)) {
                    this.MotivoAnulacionField = value;
                    this.RaisePropertyChanged("MotivoAnulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuarioCreacion {
            get {
                return this.NombreUsuarioCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioCreacionField, value) != true)) {
                    this.NombreUsuarioCreacionField = value;
                    this.RaisePropertyChanged("NombreUsuarioCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuarioSupervisor {
            get {
                return this.NombreUsuarioSupervisorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioSupervisorField, value) != true)) {
                    this.NombreUsuarioSupervisorField = value;
                    this.RaisePropertyChanged("NombreUsuarioSupervisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRFolio.FolioSegmentoType[] SegmentosFolio {
            get {
                return this.SegmentosFolioField;
            }
            set {
                if ((object.ReferenceEquals(this.SegmentosFolioField, value) != true)) {
                    this.SegmentosFolioField = value;
                    this.RaisePropertyChanged("SegmentosFolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFolios {
            get {
                return this.TotalFoliosField;
            }
            set {
                if ((this.TotalFoliosField.Equals(value) != true)) {
                    this.TotalFoliosField = value;
                    this.RaisePropertyChanged("TotalFolios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFoliosAnulados {
            get {
                return this.TotalFoliosAnuladosField;
            }
            set {
                if ((this.TotalFoliosAnuladosField.Equals(value) != true)) {
                    this.TotalFoliosAnuladosField = value;
                    this.RaisePropertyChanged("TotalFoliosAnulados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFoliosDisponibles {
            get {
                return this.TotalFoliosDisponiblesField;
            }
            set {
                if ((this.TotalFoliosDisponiblesField.Equals(value) != true)) {
                    this.TotalFoliosDisponiblesField = value;
                    this.RaisePropertyChanged("TotalFoliosDisponibles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFoliosUsados {
            get {
                return this.TotalFoliosUsadosField;
            }
            set {
                if ((this.TotalFoliosUsadosField.Equals(value) != true)) {
                    this.TotalFoliosUsadosField = value;
                    this.RaisePropertyChanged("TotalFoliosUsados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolioSegmentoType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class FolioSegmentoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsAnuladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsUltimoRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaSegmentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FolioActualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FolioFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FolioInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdFolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineaSegmentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosAnuladosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosDisponiblesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosUsadosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsAnulado {
            get {
                return this.EsAnuladoField;
            }
            set {
                if ((this.EsAnuladoField.Equals(value) != true)) {
                    this.EsAnuladoField = value;
                    this.RaisePropertyChanged("EsAnulado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsUltimoRegistro {
            get {
                return this.EsUltimoRegistroField;
            }
            set {
                if ((this.EsUltimoRegistroField.Equals(value) != true)) {
                    this.EsUltimoRegistroField = value;
                    this.RaisePropertyChanged("EsUltimoRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaSegmento {
            get {
                return this.FechaSegmentoField;
            }
            set {
                if ((this.FechaSegmentoField.Equals(value) != true)) {
                    this.FechaSegmentoField = value;
                    this.RaisePropertyChanged("FechaSegmento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FolioActual {
            get {
                return this.FolioActualField;
            }
            set {
                if ((this.FolioActualField.Equals(value) != true)) {
                    this.FolioActualField = value;
                    this.RaisePropertyChanged("FolioActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FolioFinal {
            get {
                return this.FolioFinalField;
            }
            set {
                if ((this.FolioFinalField.Equals(value) != true)) {
                    this.FolioFinalField = value;
                    this.RaisePropertyChanged("FolioFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FolioInicial {
            get {
                return this.FolioInicialField;
            }
            set {
                if ((this.FolioInicialField.Equals(value) != true)) {
                    this.FolioInicialField = value;
                    this.RaisePropertyChanged("FolioInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCaja {
            get {
                return this.IdCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCajaField, value) != true)) {
                    this.IdCajaField = value;
                    this.RaisePropertyChanged("IdCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdFolio {
            get {
                return this.IdFolioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdFolioField, value) != true)) {
                    this.IdFolioField = value;
                    this.RaisePropertyChanged("IdFolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineaSegmento {
            get {
                return this.LineaSegmentoField;
            }
            set {
                if ((this.LineaSegmentoField.Equals(value) != true)) {
                    this.LineaSegmentoField = value;
                    this.RaisePropertyChanged("LineaSegmento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCaja {
            get {
                return this.NombreCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCajaField, value) != true)) {
                    this.NombreCajaField = value;
                    this.RaisePropertyChanged("NombreCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFolios {
            get {
                return this.TotalFoliosField;
            }
            set {
                if ((this.TotalFoliosField.Equals(value) != true)) {
                    this.TotalFoliosField = value;
                    this.RaisePropertyChanged("TotalFolios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFoliosAnulados {
            get {
                return this.TotalFoliosAnuladosField;
            }
            set {
                if ((this.TotalFoliosAnuladosField.Equals(value) != true)) {
                    this.TotalFoliosAnuladosField = value;
                    this.RaisePropertyChanged("TotalFoliosAnulados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFoliosDisponibles {
            get {
                return this.TotalFoliosDisponiblesField;
            }
            set {
                if ((this.TotalFoliosDisponiblesField.Equals(value) != true)) {
                    this.TotalFoliosDisponiblesField = value;
                    this.RaisePropertyChanged("TotalFoliosDisponibles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFoliosUsados {
            get {
                return this.TotalFoliosUsadosField;
            }
            set {
                if ((this.TotalFoliosUsadosField.Equals(value) != true)) {
                    this.TotalFoliosUsadosField = value;
                    this.RaisePropertyChanged("TotalFoliosUsados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class RespuestaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocEntryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTrackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocEntry {
            get {
                return this.DocEntryField;
            }
            set {
                if ((object.ReferenceEquals(this.DocEntryField, value) != true)) {
                    this.DocEntryField = value;
                    this.RaisePropertyChanged("DocEntry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocNum {
            get {
                return this.DocNumField;
            }
            set {
                if ((object.ReferenceEquals(this.DocNumField, value) != true)) {
                    this.DocNumField = value;
                    this.RaisePropertyChanged("DocNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTrack {
            get {
                return this.IdTrackField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTrackField, value) != true)) {
                    this.IdTrackField = value;
                    this.RaisePropertyChanged("IdTrack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolioAnuladoType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class FolioAnuladoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnuladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaAnulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FolioFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FolioInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdFolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioAnulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioAprobacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineaAnulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioAnulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioAprobacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Anulado {
            get {
                return this.AnuladoField;
            }
            set {
                if ((this.AnuladoField.Equals(value) != true)) {
                    this.AnuladoField = value;
                    this.RaisePropertyChanged("Anulado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaAnulacion {
            get {
                return this.FechaAnulacionField;
            }
            set {
                if ((this.FechaAnulacionField.Equals(value) != true)) {
                    this.FechaAnulacionField = value;
                    this.RaisePropertyChanged("FechaAnulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FolioFinal {
            get {
                return this.FolioFinalField;
            }
            set {
                if ((this.FolioFinalField.Equals(value) != true)) {
                    this.FolioFinalField = value;
                    this.RaisePropertyChanged("FolioFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FolioInicial {
            get {
                return this.FolioInicialField;
            }
            set {
                if ((this.FolioInicialField.Equals(value) != true)) {
                    this.FolioInicialField = value;
                    this.RaisePropertyChanged("FolioInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCaja {
            get {
                return this.IdCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCajaField, value) != true)) {
                    this.IdCajaField = value;
                    this.RaisePropertyChanged("IdCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdFolio {
            get {
                return this.IdFolioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdFolioField, value) != true)) {
                    this.IdFolioField = value;
                    this.RaisePropertyChanged("IdFolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuarioAnulacion {
            get {
                return this.IdUsuarioAnulacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioAnulacionField, value) != true)) {
                    this.IdUsuarioAnulacionField = value;
                    this.RaisePropertyChanged("IdUsuarioAnulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuarioAprobacion {
            get {
                return this.IdUsuarioAprobacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioAprobacionField, value) != true)) {
                    this.IdUsuarioAprobacionField = value;
                    this.RaisePropertyChanged("IdUsuarioAprobacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineaAnulacion {
            get {
                return this.LineaAnulacionField;
            }
            set {
                if ((this.LineaAnulacionField.Equals(value) != true)) {
                    this.LineaAnulacionField = value;
                    this.RaisePropertyChanged("LineaAnulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motivo {
            get {
                return this.MotivoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoField, value) != true)) {
                    this.MotivoField = value;
                    this.RaisePropertyChanged("Motivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCaja {
            get {
                return this.NombreCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCajaField, value) != true)) {
                    this.NombreCajaField = value;
                    this.RaisePropertyChanged("NombreCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuarioAnulacion {
            get {
                return this.NombreUsuarioAnulacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioAnulacionField, value) != true)) {
                    this.NombreUsuarioAnulacionField = value;
                    this.RaisePropertyChanged("NombreUsuarioAnulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuarioAprobacion {
            get {
                return this.NombreUsuarioAprobacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioAprobacionField, value) != true)) {
                    this.NombreUsuarioAprobacionField = value;
                    this.RaisePropertyChanged("NombreUsuarioAprobacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolioFilterType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class FolioFilterType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FolioFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FolioInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdFolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioSupervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ObtenerSegmentosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFinal {
            get {
                return this.FechaFinalField;
            }
            set {
                if ((this.FechaFinalField.Equals(value) != true)) {
                    this.FechaFinalField = value;
                    this.RaisePropertyChanged("FechaFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FolioFinal {
            get {
                return this.FolioFinalField;
            }
            set {
                if ((this.FolioFinalField.Equals(value) != true)) {
                    this.FolioFinalField = value;
                    this.RaisePropertyChanged("FolioFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FolioInicial {
            get {
                return this.FolioInicialField;
            }
            set {
                if ((this.FolioInicialField.Equals(value) != true)) {
                    this.FolioInicialField = value;
                    this.RaisePropertyChanged("FolioInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdFolio {
            get {
                return this.IdFolioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdFolioField, value) != true)) {
                    this.IdFolioField = value;
                    this.RaisePropertyChanged("IdFolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuarioSupervisor {
            get {
                return this.IdUsuarioSupervisorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioSupervisorField, value) != true)) {
                    this.IdUsuarioSupervisorField = value;
                    this.RaisePropertyChanged("IdUsuarioSupervisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ObtenerSegmentos {
            get {
                return this.ObtenerSegmentosField;
            }
            set {
                if ((this.ObtenerSegmentosField.Equals(value) != true)) {
                    this.ObtenerSegmentosField = value;
                    this.RaisePropertyChanged("ObtenerSegmentos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolioGlobalType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class FolioGlobalType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CajaNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpisodioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FichaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CajaNombre {
            get {
                return this.CajaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.CajaNombreField, value) != true)) {
                    this.CajaNombreField = value;
                    this.RaisePropertyChanged("CajaNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Episodio {
            get {
                return this.EpisodioField;
            }
            set {
                if ((object.ReferenceEquals(this.EpisodioField, value) != true)) {
                    this.EpisodioField = value;
                    this.RaisePropertyChanged("Episodio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ficha {
            get {
                return this.FichaField;
            }
            set {
                if ((object.ReferenceEquals(this.FichaField, value) != true)) {
                    this.FichaField = value;
                    this.RaisePropertyChanged("Ficha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((this.FolioField.Equals(value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titular {
            get {
                return this.TitularField;
            }
            set {
                if ((object.ReferenceEquals(this.TitularField, value) != true)) {
                    this.TitularField = value;
                    this.RaisePropertyChanged("Titular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRFolio.IFolio")]
    public interface IFolio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/AdministrarLimiteFolio", ReplyAction="http://tempuri.org/IFolio/AdministrarLimiteFolioResponse")]
        DatosPDV.SRFolio.RespuestaType AdministrarLimiteFolio(DatosPDV.SRFolio.FolioType folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/AdministrarLimiteFolio", ReplyAction="http://tempuri.org/IFolio/AdministrarLimiteFolioResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRFolio.RespuestaType> AdministrarLimiteFolioAsync(DatosPDV.SRFolio.FolioType folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetListaLimiteFolio", ReplyAction="http://tempuri.org/IFolio/GetListaLimiteFolioResponse")]
        DatosPDV.SRFolio.FolioType[] GetListaLimiteFolio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetListaLimiteFolio", ReplyAction="http://tempuri.org/IFolio/GetListaLimiteFolioResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioType[]> GetListaLimiteFolioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetUltimoLimiteFolio", ReplyAction="http://tempuri.org/IFolio/GetUltimoLimiteFolioResponse")]
        int GetUltimoLimiteFolio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetUltimoLimiteFolio", ReplyAction="http://tempuri.org/IFolio/GetUltimoLimiteFolioResponse")]
        System.Threading.Tasks.Task<int> GetUltimoLimiteFolioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/AdministrarFolio", ReplyAction="http://tempuri.org/IFolio/AdministrarFolioResponse")]
        DatosPDV.SRFolio.RespuestaType AdministrarFolio(DatosPDV.SRFolio.FolioType folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/AdministrarFolio", ReplyAction="http://tempuri.org/IFolio/AdministrarFolioResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRFolio.RespuestaType> AdministrarFolioAsync(DatosPDV.SRFolio.FolioType folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/AdministrarFolioSegmentoMasivo", ReplyAction="http://tempuri.org/IFolio/AdministrarFolioSegmentoMasivoResponse")]
        DatosPDV.SRFolio.RespuestaType AdministrarFolioSegmentoMasivo(DatosPDV.SRFolio.FolioType[] listaFolio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/AdministrarFolioSegmentoMasivo", ReplyAction="http://tempuri.org/IFolio/AdministrarFolioSegmentoMasivoResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRFolio.RespuestaType> AdministrarFolioSegmentoMasivoAsync(DatosPDV.SRFolio.FolioType[] listaFolio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/AsignarCajaSegmentoMasivo", ReplyAction="http://tempuri.org/IFolio/AsignarCajaSegmentoMasivoResponse")]
        DatosPDV.SRFolio.RespuestaType AsignarCajaSegmentoMasivo(DatosPDV.SRFolio.FolioSegmentoType[] listaSegmento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/AsignarCajaSegmentoMasivo", ReplyAction="http://tempuri.org/IFolio/AsignarCajaSegmentoMasivoResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRFolio.RespuestaType> AsignarCajaSegmentoMasivoAsync(DatosPDV.SRFolio.FolioSegmentoType[] listaSegmento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/AnularFolio", ReplyAction="http://tempuri.org/IFolio/AnularFolioResponse")]
        DatosPDV.SRFolio.RespuestaType AnularFolio(DatosPDV.SRFolio.FolioAnuladoType folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/AnularFolio", ReplyAction="http://tempuri.org/IFolio/AnularFolioResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRFolio.RespuestaType> AnularFolioAsync(DatosPDV.SRFolio.FolioAnuladoType folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/AutorizarAnulacionFolio", ReplyAction="http://tempuri.org/IFolio/AutorizarAnulacionFolioResponse")]
        DatosPDV.SRFolio.RespuestaType AutorizarAnulacionFolio(DatosPDV.SRFolio.FolioAnuladoType folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/AutorizarAnulacionFolio", ReplyAction="http://tempuri.org/IFolio/AutorizarAnulacionFolioResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRFolio.RespuestaType> AutorizarAnulacionFolioAsync(DatosPDV.SRFolio.FolioAnuladoType folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetUltimoFolio", ReplyAction="http://tempuri.org/IFolio/GetUltimoFolioResponse")]
        int GetUltimoFolio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetUltimoFolio", ReplyAction="http://tempuri.org/IFolio/GetUltimoFolioResponse")]
        System.Threading.Tasks.Task<int> GetUltimoFolioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetListaFolios", ReplyAction="http://tempuri.org/IFolio/GetListaFoliosResponse")]
        DatosPDV.SRFolio.FolioType[] GetListaFolios(DatosPDV.SRFolio.FolioFilterType filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetListaFolios", ReplyAction="http://tempuri.org/IFolio/GetListaFoliosResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioType[]> GetListaFoliosAsync(DatosPDV.SRFolio.FolioFilterType filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetListaSegmentosByFolio", ReplyAction="http://tempuri.org/IFolio/GetListaSegmentosByFolioResponse")]
        DatosPDV.SRFolio.FolioSegmentoType[] GetListaSegmentosByFolio(string FolioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetListaSegmentosByFolio", ReplyAction="http://tempuri.org/IFolio/GetListaSegmentosByFolioResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioSegmentoType[]> GetListaSegmentosByFolioAsync(string FolioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetListaFoliosAnulados", ReplyAction="http://tempuri.org/IFolio/GetListaFoliosAnuladosResponse")]
        DatosPDV.SRFolio.FolioAnuladoType[] GetListaFoliosAnulados(DatosPDV.SRFolio.FolioFilterType folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetListaFoliosAnulados", ReplyAction="http://tempuri.org/IFolio/GetListaFoliosAnuladosResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioAnuladoType[]> GetListaFoliosAnuladosAsync(DatosPDV.SRFolio.FolioFilterType folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetListaFoliosAnuladosCajaPorSupervisor", ReplyAction="http://tempuri.org/IFolio/GetListaFoliosAnuladosCajaPorSupervisorResponse")]
        DatosPDV.SRFolio.FolioAnuladoType[] GetListaFoliosAnuladosCajaPorSupervisor(DatosPDV.SRFolio.FolioFilterType filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetListaFoliosAnuladosCajaPorSupervisor", ReplyAction="http://tempuri.org/IFolio/GetListaFoliosAnuladosCajaPorSupervisorResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioAnuladoType[]> GetListaFoliosAnuladosCajaPorSupervisorAsync(DatosPDV.SRFolio.FolioFilterType filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetSiguienteFolioByCaja", ReplyAction="http://tempuri.org/IFolio/GetSiguienteFolioByCajaResponse")]
        DatosPDV.SRFolio.FolioSegmentoType GetSiguienteFolioByCaja(string idCaja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetSiguienteFolioByCaja", ReplyAction="http://tempuri.org/IFolio/GetSiguienteFolioByCajaResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioSegmentoType> GetSiguienteFolioByCajaAsync(string idCaja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetListaFoliosCajaByUsuario", ReplyAction="http://tempuri.org/IFolio/GetListaFoliosCajaByUsuarioResponse")]
        DatosPDV.SRFolio.FolioSegmentoType[] GetListaFoliosCajaByUsuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetListaFoliosCajaByUsuario", ReplyAction="http://tempuri.org/IFolio/GetListaFoliosCajaByUsuarioResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioSegmentoType[]> GetListaFoliosCajaByUsuarioAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetListaGlobalFolio", ReplyAction="http://tempuri.org/IFolio/GetListaGlobalFolioResponse")]
        DatosPDV.SRFolio.FolioGlobalType[] GetListaGlobalFolio(int folioInicial, int folioFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolio/GetListaGlobalFolio", ReplyAction="http://tempuri.org/IFolio/GetListaGlobalFolioResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioGlobalType[]> GetListaGlobalFolioAsync(int folioInicial, int folioFinal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFolioChannel : DatosPDV.SRFolio.IFolio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FolioClient : System.ServiceModel.ClientBase<DatosPDV.SRFolio.IFolio>, DatosPDV.SRFolio.IFolio {
        
        public FolioClient() {
        }
        
        public FolioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FolioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FolioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FolioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DatosPDV.SRFolio.RespuestaType AdministrarLimiteFolio(DatosPDV.SRFolio.FolioType folio) {
            return base.Channel.AdministrarLimiteFolio(folio);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRFolio.RespuestaType> AdministrarLimiteFolioAsync(DatosPDV.SRFolio.FolioType folio) {
            return base.Channel.AdministrarLimiteFolioAsync(folio);
        }
        
        public DatosPDV.SRFolio.FolioType[] GetListaLimiteFolio() {
            return base.Channel.GetListaLimiteFolio();
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioType[]> GetListaLimiteFolioAsync() {
            return base.Channel.GetListaLimiteFolioAsync();
        }
        
        public int GetUltimoLimiteFolio() {
            return base.Channel.GetUltimoLimiteFolio();
        }
        
        public System.Threading.Tasks.Task<int> GetUltimoLimiteFolioAsync() {
            return base.Channel.GetUltimoLimiteFolioAsync();
        }
        
        public DatosPDV.SRFolio.RespuestaType AdministrarFolio(DatosPDV.SRFolio.FolioType folio) {
            return base.Channel.AdministrarFolio(folio);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRFolio.RespuestaType> AdministrarFolioAsync(DatosPDV.SRFolio.FolioType folio) {
            return base.Channel.AdministrarFolioAsync(folio);
        }
        
        public DatosPDV.SRFolio.RespuestaType AdministrarFolioSegmentoMasivo(DatosPDV.SRFolio.FolioType[] listaFolio) {
            return base.Channel.AdministrarFolioSegmentoMasivo(listaFolio);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRFolio.RespuestaType> AdministrarFolioSegmentoMasivoAsync(DatosPDV.SRFolio.FolioType[] listaFolio) {
            return base.Channel.AdministrarFolioSegmentoMasivoAsync(listaFolio);
        }
        
        public DatosPDV.SRFolio.RespuestaType AsignarCajaSegmentoMasivo(DatosPDV.SRFolio.FolioSegmentoType[] listaSegmento) {
            return base.Channel.AsignarCajaSegmentoMasivo(listaSegmento);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRFolio.RespuestaType> AsignarCajaSegmentoMasivoAsync(DatosPDV.SRFolio.FolioSegmentoType[] listaSegmento) {
            return base.Channel.AsignarCajaSegmentoMasivoAsync(listaSegmento);
        }
        
        public DatosPDV.SRFolio.RespuestaType AnularFolio(DatosPDV.SRFolio.FolioAnuladoType folio) {
            return base.Channel.AnularFolio(folio);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRFolio.RespuestaType> AnularFolioAsync(DatosPDV.SRFolio.FolioAnuladoType folio) {
            return base.Channel.AnularFolioAsync(folio);
        }
        
        public DatosPDV.SRFolio.RespuestaType AutorizarAnulacionFolio(DatosPDV.SRFolio.FolioAnuladoType folio) {
            return base.Channel.AutorizarAnulacionFolio(folio);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRFolio.RespuestaType> AutorizarAnulacionFolioAsync(DatosPDV.SRFolio.FolioAnuladoType folio) {
            return base.Channel.AutorizarAnulacionFolioAsync(folio);
        }
        
        public int GetUltimoFolio() {
            return base.Channel.GetUltimoFolio();
        }
        
        public System.Threading.Tasks.Task<int> GetUltimoFolioAsync() {
            return base.Channel.GetUltimoFolioAsync();
        }
        
        public DatosPDV.SRFolio.FolioType[] GetListaFolios(DatosPDV.SRFolio.FolioFilterType filtro) {
            return base.Channel.GetListaFolios(filtro);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioType[]> GetListaFoliosAsync(DatosPDV.SRFolio.FolioFilterType filtro) {
            return base.Channel.GetListaFoliosAsync(filtro);
        }
        
        public DatosPDV.SRFolio.FolioSegmentoType[] GetListaSegmentosByFolio(string FolioId) {
            return base.Channel.GetListaSegmentosByFolio(FolioId);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioSegmentoType[]> GetListaSegmentosByFolioAsync(string FolioId) {
            return base.Channel.GetListaSegmentosByFolioAsync(FolioId);
        }
        
        public DatosPDV.SRFolio.FolioAnuladoType[] GetListaFoliosAnulados(DatosPDV.SRFolio.FolioFilterType folio) {
            return base.Channel.GetListaFoliosAnulados(folio);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioAnuladoType[]> GetListaFoliosAnuladosAsync(DatosPDV.SRFolio.FolioFilterType folio) {
            return base.Channel.GetListaFoliosAnuladosAsync(folio);
        }
        
        public DatosPDV.SRFolio.FolioAnuladoType[] GetListaFoliosAnuladosCajaPorSupervisor(DatosPDV.SRFolio.FolioFilterType filtro) {
            return base.Channel.GetListaFoliosAnuladosCajaPorSupervisor(filtro);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioAnuladoType[]> GetListaFoliosAnuladosCajaPorSupervisorAsync(DatosPDV.SRFolio.FolioFilterType filtro) {
            return base.Channel.GetListaFoliosAnuladosCajaPorSupervisorAsync(filtro);
        }
        
        public DatosPDV.SRFolio.FolioSegmentoType GetSiguienteFolioByCaja(string idCaja) {
            return base.Channel.GetSiguienteFolioByCaja(idCaja);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioSegmentoType> GetSiguienteFolioByCajaAsync(string idCaja) {
            return base.Channel.GetSiguienteFolioByCajaAsync(idCaja);
        }
        
        public DatosPDV.SRFolio.FolioSegmentoType[] GetListaFoliosCajaByUsuario(string usuario) {
            return base.Channel.GetListaFoliosCajaByUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioSegmentoType[]> GetListaFoliosCajaByUsuarioAsync(string usuario) {
            return base.Channel.GetListaFoliosCajaByUsuarioAsync(usuario);
        }
        
        public DatosPDV.SRFolio.FolioGlobalType[] GetListaGlobalFolio(int folioInicial, int folioFinal) {
            return base.Channel.GetListaGlobalFolio(folioInicial, folioFinal);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRFolio.FolioGlobalType[]> GetListaGlobalFolioAsync(int folioInicial, int folioFinal) {
            return base.Channel.GetListaGlobalFolioAsync(folioInicial, folioFinal);
        }
    }
}
