//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosPDV.SRCaja {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CajaType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DatosPDV.SRCaja.AsignacionCajaType))]
    public partial class CajaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRCaja.FolioType FolioSiguienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<DatosPDV.SRCaja.FolioType> FoliosCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuncionDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HabilitaCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdFuncionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdSeccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdSupervisorCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreSupervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroMACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PisoDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeccionDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRCaja.FolioType FolioSiguiente {
            get {
                return this.FolioSiguienteField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioSiguienteField, value) != true)) {
                    this.FolioSiguienteField = value;
                    this.RaisePropertyChanged("FolioSiguiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DatosPDV.SRCaja.FolioType> FoliosCaja {
            get {
                return this.FoliosCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.FoliosCajaField, value) != true)) {
                    this.FoliosCajaField = value;
                    this.RaisePropertyChanged("FoliosCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuncionDescripcion {
            get {
                return this.FuncionDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncionDescripcionField, value) != true)) {
                    this.FuncionDescripcionField = value;
                    this.RaisePropertyChanged("FuncionDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HabilitaCaja {
            get {
                return this.HabilitaCajaField;
            }
            set {
                if ((this.HabilitaCajaField.Equals(value) != true)) {
                    this.HabilitaCajaField = value;
                    this.RaisePropertyChanged("HabilitaCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCaja {
            get {
                return this.IdCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCajaField, value) != true)) {
                    this.IdCajaField = value;
                    this.RaisePropertyChanged("IdCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdFuncion {
            get {
                return this.IdFuncionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdFuncionField, value) != true)) {
                    this.IdFuncionField = value;
                    this.RaisePropertyChanged("IdFuncion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPiso {
            get {
                return this.IdPisoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPisoField, value) != true)) {
                    this.IdPisoField = value;
                    this.RaisePropertyChanged("IdPiso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdSeccion {
            get {
                return this.IdSeccionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSeccionField, value) != true)) {
                    this.IdSeccionField = value;
                    this.RaisePropertyChanged("IdSeccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdSupervisorCaja {
            get {
                return this.IdSupervisorCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSupervisorCajaField, value) != true)) {
                    this.IdSupervisorCajaField = value;
                    this.RaisePropertyChanged("IdSupervisorCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTipo {
            get {
                return this.IdTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTipoField, value) != true)) {
                    this.IdTipoField = value;
                    this.RaisePropertyChanged("IdTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCaja {
            get {
                return this.NombreCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCajaField, value) != true)) {
                    this.NombreCajaField = value;
                    this.RaisePropertyChanged("NombreCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreSupervisor {
            get {
                return this.NombreSupervisorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreSupervisorField, value) != true)) {
                    this.NombreSupervisorField = value;
                    this.RaisePropertyChanged("NombreSupervisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroIP {
            get {
                return this.NumeroIPField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroIPField, value) != true)) {
                    this.NumeroIPField = value;
                    this.RaisePropertyChanged("NumeroIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroMAC {
            get {
                return this.NumeroMACField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroMACField, value) != true)) {
                    this.NumeroMACField = value;
                    this.RaisePropertyChanged("NumeroMAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PisoDescripcion {
            get {
                return this.PisoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.PisoDescripcionField, value) != true)) {
                    this.PisoDescripcionField = value;
                    this.RaisePropertyChanged("PisoDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeccionDescripcion {
            get {
                return this.SeccionDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.SeccionDescripcionField, value) != true)) {
                    this.SeccionDescripcionField = value;
                    this.RaisePropertyChanged("SeccionDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDescripcion {
            get {
                return this.TipoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDescripcionField, value) != true)) {
                    this.TipoDescripcionField = value;
                    this.RaisePropertyChanged("TipoDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolioType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class FolioType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CajaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CajaNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadSegmentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadSegmentoPendientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsAnuladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsUltimoRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FolioFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FolioInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdFolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioSupervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoAnulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioSupervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<DatosPDV.SRCaja.FolioSegmentoType> SegmentosFolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosAnuladosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosDisponiblesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosUsadosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CajaId {
            get {
                return this.CajaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CajaIdField, value) != true)) {
                    this.CajaIdField = value;
                    this.RaisePropertyChanged("CajaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CajaNombre {
            get {
                return this.CajaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.CajaNombreField, value) != true)) {
                    this.CajaNombreField = value;
                    this.RaisePropertyChanged("CajaNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CantidadSegmento {
            get {
                return this.CantidadSegmentoField;
            }
            set {
                if ((this.CantidadSegmentoField.Equals(value) != true)) {
                    this.CantidadSegmentoField = value;
                    this.RaisePropertyChanged("CantidadSegmento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CantidadSegmentoPendientes {
            get {
                return this.CantidadSegmentoPendientesField;
            }
            set {
                if ((this.CantidadSegmentoPendientesField.Equals(value) != true)) {
                    this.CantidadSegmentoPendientesField = value;
                    this.RaisePropertyChanged("CantidadSegmentoPendientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsAnulado {
            get {
                return this.EsAnuladoField;
            }
            set {
                if ((this.EsAnuladoField.Equals(value) != true)) {
                    this.EsAnuladoField = value;
                    this.RaisePropertyChanged("EsAnulado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsUltimoRegistro {
            get {
                return this.EsUltimoRegistroField;
            }
            set {
                if ((this.EsUltimoRegistroField.Equals(value) != true)) {
                    this.EsUltimoRegistroField = value;
                    this.RaisePropertyChanged("EsUltimoRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFolio {
            get {
                return this.FechaFolioField;
            }
            set {
                if ((this.FechaFolioField.Equals(value) != true)) {
                    this.FechaFolioField = value;
                    this.RaisePropertyChanged("FechaFolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FolioFinal {
            get {
                return this.FolioFinalField;
            }
            set {
                if ((this.FolioFinalField.Equals(value) != true)) {
                    this.FolioFinalField = value;
                    this.RaisePropertyChanged("FolioFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FolioInicial {
            get {
                return this.FolioInicialField;
            }
            set {
                if ((this.FolioInicialField.Equals(value) != true)) {
                    this.FolioInicialField = value;
                    this.RaisePropertyChanged("FolioInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdFolio {
            get {
                return this.IdFolioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdFolioField, value) != true)) {
                    this.IdFolioField = value;
                    this.RaisePropertyChanged("IdFolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuarioCreacion {
            get {
                return this.IdUsuarioCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioCreacionField, value) != true)) {
                    this.IdUsuarioCreacionField = value;
                    this.RaisePropertyChanged("IdUsuarioCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuarioSupervisor {
            get {
                return this.IdUsuarioSupervisorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioSupervisorField, value) != true)) {
                    this.IdUsuarioSupervisorField = value;
                    this.RaisePropertyChanged("IdUsuarioSupervisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoAnulacion {
            get {
                return this.MotivoAnulacionField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoAnulacionField, value) != true)) {
                    this.MotivoAnulacionField = value;
                    this.RaisePropertyChanged("MotivoAnulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuarioCreacion {
            get {
                return this.NombreUsuarioCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioCreacionField, value) != true)) {
                    this.NombreUsuarioCreacionField = value;
                    this.RaisePropertyChanged("NombreUsuarioCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuarioSupervisor {
            get {
                return this.NombreUsuarioSupervisorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioSupervisorField, value) != true)) {
                    this.NombreUsuarioSupervisorField = value;
                    this.RaisePropertyChanged("NombreUsuarioSupervisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DatosPDV.SRCaja.FolioSegmentoType> SegmentosFolio {
            get {
                return this.SegmentosFolioField;
            }
            set {
                if ((object.ReferenceEquals(this.SegmentosFolioField, value) != true)) {
                    this.SegmentosFolioField = value;
                    this.RaisePropertyChanged("SegmentosFolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFolios {
            get {
                return this.TotalFoliosField;
            }
            set {
                if ((this.TotalFoliosField.Equals(value) != true)) {
                    this.TotalFoliosField = value;
                    this.RaisePropertyChanged("TotalFolios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFoliosAnulados {
            get {
                return this.TotalFoliosAnuladosField;
            }
            set {
                if ((this.TotalFoliosAnuladosField.Equals(value) != true)) {
                    this.TotalFoliosAnuladosField = value;
                    this.RaisePropertyChanged("TotalFoliosAnulados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFoliosDisponibles {
            get {
                return this.TotalFoliosDisponiblesField;
            }
            set {
                if ((this.TotalFoliosDisponiblesField.Equals(value) != true)) {
                    this.TotalFoliosDisponiblesField = value;
                    this.RaisePropertyChanged("TotalFoliosDisponibles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFoliosUsados {
            get {
                return this.TotalFoliosUsadosField;
            }
            set {
                if ((this.TotalFoliosUsadosField.Equals(value) != true)) {
                    this.TotalFoliosUsadosField = value;
                    this.RaisePropertyChanged("TotalFoliosUsados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AsignacionCajaType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class AsignacionCajaType : DatosPDV.SRCaja.CajaType {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoAsignacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaAsignacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaAsignacionDiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCierreCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCierreEfectivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaInicioCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaRechazoCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdAsignacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioAsignadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MontoCierreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MontoDiferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MontoInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MontoRecaudadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioAsignadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroMaquinaTransbankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionDiferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionRechazoCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RangoFolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RangoFolioRestanteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoAsignacion {
            get {
                return this.EstadoAsignacionField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoAsignacionField, value) != true)) {
                    this.EstadoAsignacionField = value;
                    this.RaisePropertyChanged("EstadoAsignacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaAsignacion {
            get {
                return this.FechaAsignacionField;
            }
            set {
                if ((this.FechaAsignacionField.Equals(value) != true)) {
                    this.FechaAsignacionField = value;
                    this.RaisePropertyChanged("FechaAsignacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaAsignacionDia {
            get {
                return this.FechaAsignacionDiaField;
            }
            set {
                if ((this.FechaAsignacionDiaField.Equals(value) != true)) {
                    this.FechaAsignacionDiaField = value;
                    this.RaisePropertyChanged("FechaAsignacionDia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCierreCaja {
            get {
                return this.FechaCierreCajaField;
            }
            set {
                if ((this.FechaCierreCajaField.Equals(value) != true)) {
                    this.FechaCierreCajaField = value;
                    this.RaisePropertyChanged("FechaCierreCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCierreEfectivo {
            get {
                return this.FechaCierreEfectivoField;
            }
            set {
                if ((this.FechaCierreEfectivoField.Equals(value) != true)) {
                    this.FechaCierreEfectivoField = value;
                    this.RaisePropertyChanged("FechaCierreEfectivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaInicioCaja {
            get {
                return this.FechaInicioCajaField;
            }
            set {
                if ((this.FechaInicioCajaField.Equals(value) != true)) {
                    this.FechaInicioCajaField = value;
                    this.RaisePropertyChanged("FechaInicioCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaRechazoCaja {
            get {
                return this.FechaRechazoCajaField;
            }
            set {
                if ((this.FechaRechazoCajaField.Equals(value) != true)) {
                    this.FechaRechazoCajaField = value;
                    this.RaisePropertyChanged("FechaRechazoCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdAsignacion {
            get {
                return this.IdAsignacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdAsignacionField, value) != true)) {
                    this.IdAsignacionField = value;
                    this.RaisePropertyChanged("IdAsignacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuarioAsignado {
            get {
                return this.IdUsuarioAsignadoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioAsignadoField, value) != true)) {
                    this.IdUsuarioAsignadoField = value;
                    this.RaisePropertyChanged("IdUsuarioAsignado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MontoCierre {
            get {
                return this.MontoCierreField;
            }
            set {
                if ((this.MontoCierreField.Equals(value) != true)) {
                    this.MontoCierreField = value;
                    this.RaisePropertyChanged("MontoCierre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MontoDiferencia {
            get {
                return this.MontoDiferenciaField;
            }
            set {
                if ((this.MontoDiferenciaField.Equals(value) != true)) {
                    this.MontoDiferenciaField = value;
                    this.RaisePropertyChanged("MontoDiferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MontoInicial {
            get {
                return this.MontoInicialField;
            }
            set {
                if ((this.MontoInicialField.Equals(value) != true)) {
                    this.MontoInicialField = value;
                    this.RaisePropertyChanged("MontoInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MontoRecaudado {
            get {
                return this.MontoRecaudadoField;
            }
            set {
                if ((this.MontoRecaudadoField.Equals(value) != true)) {
                    this.MontoRecaudadoField = value;
                    this.RaisePropertyChanged("MontoRecaudado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuarioAsignado {
            get {
                return this.NombreUsuarioAsignadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioAsignadoField, value) != true)) {
                    this.NombreUsuarioAsignadoField = value;
                    this.RaisePropertyChanged("NombreUsuarioAsignado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroMaquinaTransbank {
            get {
                return this.NumeroMaquinaTransbankField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroMaquinaTransbankField, value) != true)) {
                    this.NumeroMaquinaTransbankField = value;
                    this.RaisePropertyChanged("NumeroMaquinaTransbank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionDiferencia {
            get {
                return this.ObservacionDiferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionDiferenciaField, value) != true)) {
                    this.ObservacionDiferenciaField = value;
                    this.RaisePropertyChanged("ObservacionDiferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionRechazoCaja {
            get {
                return this.ObservacionRechazoCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionRechazoCajaField, value) != true)) {
                    this.ObservacionRechazoCajaField = value;
                    this.RaisePropertyChanged("ObservacionRechazoCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RangoFolio {
            get {
                return this.RangoFolioField;
            }
            set {
                if ((object.ReferenceEquals(this.RangoFolioField, value) != true)) {
                    this.RangoFolioField = value;
                    this.RaisePropertyChanged("RangoFolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RangoFolioRestante {
            get {
                return this.RangoFolioRestanteField;
            }
            set {
                if ((object.ReferenceEquals(this.RangoFolioRestanteField, value) != true)) {
                    this.RangoFolioRestanteField = value;
                    this.RaisePropertyChanged("RangoFolioRestante");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolioSegmentoType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class FolioSegmentoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsAnuladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsUltimoRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaSegmentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FolioActualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FolioFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FolioInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdFolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineaSegmentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosAnuladosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosDisponiblesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFoliosUsadosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsAnulado {
            get {
                return this.EsAnuladoField;
            }
            set {
                if ((this.EsAnuladoField.Equals(value) != true)) {
                    this.EsAnuladoField = value;
                    this.RaisePropertyChanged("EsAnulado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsUltimoRegistro {
            get {
                return this.EsUltimoRegistroField;
            }
            set {
                if ((this.EsUltimoRegistroField.Equals(value) != true)) {
                    this.EsUltimoRegistroField = value;
                    this.RaisePropertyChanged("EsUltimoRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaSegmento {
            get {
                return this.FechaSegmentoField;
            }
            set {
                if ((this.FechaSegmentoField.Equals(value) != true)) {
                    this.FechaSegmentoField = value;
                    this.RaisePropertyChanged("FechaSegmento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FolioActual {
            get {
                return this.FolioActualField;
            }
            set {
                if ((this.FolioActualField.Equals(value) != true)) {
                    this.FolioActualField = value;
                    this.RaisePropertyChanged("FolioActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FolioFinal {
            get {
                return this.FolioFinalField;
            }
            set {
                if ((this.FolioFinalField.Equals(value) != true)) {
                    this.FolioFinalField = value;
                    this.RaisePropertyChanged("FolioFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FolioInicial {
            get {
                return this.FolioInicialField;
            }
            set {
                if ((this.FolioInicialField.Equals(value) != true)) {
                    this.FolioInicialField = value;
                    this.RaisePropertyChanged("FolioInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCaja {
            get {
                return this.IdCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCajaField, value) != true)) {
                    this.IdCajaField = value;
                    this.RaisePropertyChanged("IdCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdFolio {
            get {
                return this.IdFolioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdFolioField, value) != true)) {
                    this.IdFolioField = value;
                    this.RaisePropertyChanged("IdFolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineaSegmento {
            get {
                return this.LineaSegmentoField;
            }
            set {
                if ((this.LineaSegmentoField.Equals(value) != true)) {
                    this.LineaSegmentoField = value;
                    this.RaisePropertyChanged("LineaSegmento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCaja {
            get {
                return this.NombreCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCajaField, value) != true)) {
                    this.NombreCajaField = value;
                    this.RaisePropertyChanged("NombreCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFolios {
            get {
                return this.TotalFoliosField;
            }
            set {
                if ((this.TotalFoliosField.Equals(value) != true)) {
                    this.TotalFoliosField = value;
                    this.RaisePropertyChanged("TotalFolios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFoliosAnulados {
            get {
                return this.TotalFoliosAnuladosField;
            }
            set {
                if ((this.TotalFoliosAnuladosField.Equals(value) != true)) {
                    this.TotalFoliosAnuladosField = value;
                    this.RaisePropertyChanged("TotalFoliosAnulados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFoliosDisponibles {
            get {
                return this.TotalFoliosDisponiblesField;
            }
            set {
                if ((this.TotalFoliosDisponiblesField.Equals(value) != true)) {
                    this.TotalFoliosDisponiblesField = value;
                    this.RaisePropertyChanged("TotalFoliosDisponibles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFoliosUsados {
            get {
                return this.TotalFoliosUsadosField;
            }
            set {
                if ((this.TotalFoliosUsadosField.Equals(value) != true)) {
                    this.TotalFoliosUsadosField = value;
                    this.RaisePropertyChanged("TotalFoliosUsados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class RespuestaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocEntryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTrackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocEntry {
            get {
                return this.DocEntryField;
            }
            set {
                if ((object.ReferenceEquals(this.DocEntryField, value) != true)) {
                    this.DocEntryField = value;
                    this.RaisePropertyChanged("DocEntry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocNum {
            get {
                return this.DocNumField;
            }
            set {
                if ((object.ReferenceEquals(this.DocNumField, value) != true)) {
                    this.DocNumField = value;
                    this.RaisePropertyChanged("DocNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTrack {
            get {
                return this.IdTrackField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTrackField, value) != true)) {
                    this.IdTrackField = value;
                    this.RaisePropertyChanged("IdTrack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AsignacionCajaFilterType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class AsignacionCajaFilterType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsVigenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaAsignacionFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaAsignacionInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCierreFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCierreInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdAsignacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdSupervisorCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioAsignadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsVigente {
            get {
                return this.EsVigenteField;
            }
            set {
                if ((this.EsVigenteField.Equals(value) != true)) {
                    this.EsVigenteField = value;
                    this.RaisePropertyChanged("EsVigente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaAsignacionFinal {
            get {
                return this.FechaAsignacionFinalField;
            }
            set {
                if ((this.FechaAsignacionFinalField.Equals(value) != true)) {
                    this.FechaAsignacionFinalField = value;
                    this.RaisePropertyChanged("FechaAsignacionFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaAsignacionInicio {
            get {
                return this.FechaAsignacionInicioField;
            }
            set {
                if ((this.FechaAsignacionInicioField.Equals(value) != true)) {
                    this.FechaAsignacionInicioField = value;
                    this.RaisePropertyChanged("FechaAsignacionInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCierreFinal {
            get {
                return this.FechaCierreFinalField;
            }
            set {
                if ((this.FechaCierreFinalField.Equals(value) != true)) {
                    this.FechaCierreFinalField = value;
                    this.RaisePropertyChanged("FechaCierreFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCierreInicio {
            get {
                return this.FechaCierreInicioField;
            }
            set {
                if ((this.FechaCierreInicioField.Equals(value) != true)) {
                    this.FechaCierreInicioField = value;
                    this.RaisePropertyChanged("FechaCierreInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdAsignacion {
            get {
                return this.IdAsignacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdAsignacionField, value) != true)) {
                    this.IdAsignacionField = value;
                    this.RaisePropertyChanged("IdAsignacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCaja {
            get {
                return this.IdCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCajaField, value) != true)) {
                    this.IdCajaField = value;
                    this.RaisePropertyChanged("IdCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdSupervisorCaja {
            get {
                return this.IdSupervisorCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSupervisorCajaField, value) != true)) {
                    this.IdSupervisorCajaField = value;
                    this.RaisePropertyChanged("IdSupervisorCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuarioAsignado {
            get {
                return this.IdUsuarioAsignadoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioAsignadoField, value) != true)) {
                    this.IdUsuarioAsignadoField = value;
                    this.RaisePropertyChanged("IdUsuarioAsignado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MontoCierreType", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    [System.SerializableAttribute()]
    public partial class MontoCierreType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatosPDV.SRCaja.TipoMontoCierre TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatosPDV.SRCaja.TipoMontoCierre Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoMontoCierre", Namespace="http://schemas.datacontract.org/2004/07/PDVWebService.Mensajes")]
    public enum TipoMontoCierre : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ninguno = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Documento = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRCaja.ICaja")]
    public interface ICaja {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/GetListaCajas", ReplyAction="http://tempuri.org/ICaja/GetListaCajasResponse")]
        System.Collections.Generic.List<DatosPDV.SRCaja.CajaType> GetListaCajas(DatosPDV.SRCaja.CajaType caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/GetListaCajas", ReplyAction="http://tempuri.org/ICaja/GetListaCajasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRCaja.CajaType>> GetListaCajasAsync(DatosPDV.SRCaja.CajaType caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/AdministrarCaja", ReplyAction="http://tempuri.org/ICaja/AdministrarCajaResponse")]
        DatosPDV.SRCaja.RespuestaType AdministrarCaja(DatosPDV.SRCaja.CajaType caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/AdministrarCaja", ReplyAction="http://tempuri.org/ICaja/AdministrarCajaResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRCaja.RespuestaType> AdministrarCajaAsync(DatosPDV.SRCaja.CajaType caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/AdministrarCajaMasivoSupervisor", ReplyAction="http://tempuri.org/ICaja/AdministrarCajaMasivoSupervisorResponse")]
        DatosPDV.SRCaja.RespuestaType AdministrarCajaMasivoSupervisor(System.Collections.Generic.List<DatosPDV.SRCaja.CajaType> cajas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/AdministrarCajaMasivoSupervisor", ReplyAction="http://tempuri.org/ICaja/AdministrarCajaMasivoSupervisorResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRCaja.RespuestaType> AdministrarCajaMasivoSupervisorAsync(System.Collections.Generic.List<DatosPDV.SRCaja.CajaType> cajas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/GetCajaByParams", ReplyAction="http://tempuri.org/ICaja/GetCajaByParamsResponse")]
        DatosPDV.SRCaja.CajaType GetCajaByParams(DatosPDV.SRCaja.CajaType cajaSeach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/GetCajaByParams", ReplyAction="http://tempuri.org/ICaja/GetCajaByParamsResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRCaja.CajaType> GetCajaByParamsAsync(DatosPDV.SRCaja.CajaType cajaSeach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/AsignarCaja", ReplyAction="http://tempuri.org/ICaja/AsignarCajaResponse")]
        DatosPDV.SRCaja.RespuestaType AsignarCaja(DatosPDV.SRCaja.AsignacionCajaType caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/AsignarCaja", ReplyAction="http://tempuri.org/ICaja/AsignarCajaResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRCaja.RespuestaType> AsignarCajaAsync(DatosPDV.SRCaja.AsignacionCajaType caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/AsignarCajaCierre", ReplyAction="http://tempuri.org/ICaja/AsignarCajaCierreResponse")]
        DatosPDV.SRCaja.RespuestaType AsignarCajaCierre(DatosPDV.SRCaja.AsignacionCajaType caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/AsignarCajaCierre", ReplyAction="http://tempuri.org/ICaja/AsignarCajaCierreResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRCaja.RespuestaType> AsignarCajaCierreAsync(DatosPDV.SRCaja.AsignacionCajaType caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/AsignarCajaAjusteCierre", ReplyAction="http://tempuri.org/ICaja/AsignarCajaAjusteCierreResponse")]
        DatosPDV.SRCaja.RespuestaType AsignarCajaAjusteCierre(DatosPDV.SRCaja.AsignacionCajaType caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/AsignarCajaAjusteCierre", ReplyAction="http://tempuri.org/ICaja/AsignarCajaAjusteCierreResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRCaja.RespuestaType> AsignarCajaAjusteCierreAsync(DatosPDV.SRCaja.AsignacionCajaType caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/AsignarCajaMasivo", ReplyAction="http://tempuri.org/ICaja/AsignarCajaMasivoResponse")]
        DatosPDV.SRCaja.RespuestaType AsignarCajaMasivo(System.Collections.Generic.List<DatosPDV.SRCaja.AsignacionCajaType> asignaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/AsignarCajaMasivo", ReplyAction="http://tempuri.org/ICaja/AsignarCajaMasivoResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRCaja.RespuestaType> AsignarCajaMasivoAsync(System.Collections.Generic.List<DatosPDV.SRCaja.AsignacionCajaType> asignaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/GetListaCajaAsignadas", ReplyAction="http://tempuri.org/ICaja/GetListaCajaAsignadasResponse")]
        System.Collections.Generic.List<DatosPDV.SRCaja.AsignacionCajaType> GetListaCajaAsignadas(DatosPDV.SRCaja.AsignacionCajaFilterType cajaSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/GetListaCajaAsignadas", ReplyAction="http://tempuri.org/ICaja/GetListaCajaAsignadasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRCaja.AsignacionCajaType>> GetListaCajaAsignadasAsync(DatosPDV.SRCaja.AsignacionCajaFilterType cajaSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/GetCajaAsignadaById", ReplyAction="http://tempuri.org/ICaja/GetCajaAsignadaByIdResponse")]
        DatosPDV.SRCaja.AsignacionCajaType GetCajaAsignadaById(string IdAsignacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/GetCajaAsignadaById", ReplyAction="http://tempuri.org/ICaja/GetCajaAsignadaByIdResponse")]
        System.Threading.Tasks.Task<DatosPDV.SRCaja.AsignacionCajaType> GetCajaAsignadaByIdAsync(string IdAsignacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/GetCajaMontoCierre", ReplyAction="http://tempuri.org/ICaja/GetCajaMontoCierreResponse")]
        System.Collections.Generic.List<DatosPDV.SRCaja.MontoCierreType> GetCajaMontoCierre(string AsignacionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaja/GetCajaMontoCierre", ReplyAction="http://tempuri.org/ICaja/GetCajaMontoCierreResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRCaja.MontoCierreType>> GetCajaMontoCierreAsync(string AsignacionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICajaChannel : DatosPDV.SRCaja.ICaja, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CajaClient : System.ServiceModel.ClientBase<DatosPDV.SRCaja.ICaja>, DatosPDV.SRCaja.ICaja {
        
        public CajaClient() {
        }
        
        public CajaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CajaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CajaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CajaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<DatosPDV.SRCaja.CajaType> GetListaCajas(DatosPDV.SRCaja.CajaType caja) {
            return base.Channel.GetListaCajas(caja);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRCaja.CajaType>> GetListaCajasAsync(DatosPDV.SRCaja.CajaType caja) {
            return base.Channel.GetListaCajasAsync(caja);
        }
        
        public DatosPDV.SRCaja.RespuestaType AdministrarCaja(DatosPDV.SRCaja.CajaType caja) {
            return base.Channel.AdministrarCaja(caja);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRCaja.RespuestaType> AdministrarCajaAsync(DatosPDV.SRCaja.CajaType caja) {
            return base.Channel.AdministrarCajaAsync(caja);
        }
        
        public DatosPDV.SRCaja.RespuestaType AdministrarCajaMasivoSupervisor(System.Collections.Generic.List<DatosPDV.SRCaja.CajaType> cajas) {
            return base.Channel.AdministrarCajaMasivoSupervisor(cajas);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRCaja.RespuestaType> AdministrarCajaMasivoSupervisorAsync(System.Collections.Generic.List<DatosPDV.SRCaja.CajaType> cajas) {
            return base.Channel.AdministrarCajaMasivoSupervisorAsync(cajas);
        }
        
        public DatosPDV.SRCaja.CajaType GetCajaByParams(DatosPDV.SRCaja.CajaType cajaSeach) {
            return base.Channel.GetCajaByParams(cajaSeach);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRCaja.CajaType> GetCajaByParamsAsync(DatosPDV.SRCaja.CajaType cajaSeach) {
            return base.Channel.GetCajaByParamsAsync(cajaSeach);
        }
        
        public DatosPDV.SRCaja.RespuestaType AsignarCaja(DatosPDV.SRCaja.AsignacionCajaType caja) {
            return base.Channel.AsignarCaja(caja);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRCaja.RespuestaType> AsignarCajaAsync(DatosPDV.SRCaja.AsignacionCajaType caja) {
            return base.Channel.AsignarCajaAsync(caja);
        }
        
        public DatosPDV.SRCaja.RespuestaType AsignarCajaCierre(DatosPDV.SRCaja.AsignacionCajaType caja) {
            return base.Channel.AsignarCajaCierre(caja);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRCaja.RespuestaType> AsignarCajaCierreAsync(DatosPDV.SRCaja.AsignacionCajaType caja) {
            return base.Channel.AsignarCajaCierreAsync(caja);
        }
        
        public DatosPDV.SRCaja.RespuestaType AsignarCajaAjusteCierre(DatosPDV.SRCaja.AsignacionCajaType caja) {
            return base.Channel.AsignarCajaAjusteCierre(caja);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRCaja.RespuestaType> AsignarCajaAjusteCierreAsync(DatosPDV.SRCaja.AsignacionCajaType caja) {
            return base.Channel.AsignarCajaAjusteCierreAsync(caja);
        }
        
        public DatosPDV.SRCaja.RespuestaType AsignarCajaMasivo(System.Collections.Generic.List<DatosPDV.SRCaja.AsignacionCajaType> asignaciones) {
            return base.Channel.AsignarCajaMasivo(asignaciones);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRCaja.RespuestaType> AsignarCajaMasivoAsync(System.Collections.Generic.List<DatosPDV.SRCaja.AsignacionCajaType> asignaciones) {
            return base.Channel.AsignarCajaMasivoAsync(asignaciones);
        }
        
        public System.Collections.Generic.List<DatosPDV.SRCaja.AsignacionCajaType> GetListaCajaAsignadas(DatosPDV.SRCaja.AsignacionCajaFilterType cajaSearch) {
            return base.Channel.GetListaCajaAsignadas(cajaSearch);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRCaja.AsignacionCajaType>> GetListaCajaAsignadasAsync(DatosPDV.SRCaja.AsignacionCajaFilterType cajaSearch) {
            return base.Channel.GetListaCajaAsignadasAsync(cajaSearch);
        }
        
        public DatosPDV.SRCaja.AsignacionCajaType GetCajaAsignadaById(string IdAsignacion) {
            return base.Channel.GetCajaAsignadaById(IdAsignacion);
        }
        
        public System.Threading.Tasks.Task<DatosPDV.SRCaja.AsignacionCajaType> GetCajaAsignadaByIdAsync(string IdAsignacion) {
            return base.Channel.GetCajaAsignadaByIdAsync(IdAsignacion);
        }
        
        public System.Collections.Generic.List<DatosPDV.SRCaja.MontoCierreType> GetCajaMontoCierre(string AsignacionId) {
            return base.Channel.GetCajaMontoCierre(AsignacionId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DatosPDV.SRCaja.MontoCierreType>> GetCajaMontoCierreAsync(string AsignacionId) {
            return base.Channel.GetCajaMontoCierreAsync(AsignacionId);
        }
    }
}
